<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://openiaml.org/model0.4" nsPrefix="iaml">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true"
      eSuperTypes="#//GeneratedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An element with a name."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdge" abstract="true" eSuperTypes="#//GeneratedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents some higher-level relationship between two components."/>
    </eAnnotations>
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.4.2 to abstract"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//WireEdgesSource"
        eOpposite="#//WireEdgesSource/outEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//WireEdgeDestination"
        eOpposite="#//WireEdgeDestination/inEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgeDestination" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEdges" upperBound="-1"
        eType="#//WireEdge" eOpposite="#//WireEdge/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgesSource" abstract="true" interface="true"
      eSuperTypes="#//ShouldntContainWires">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="temporarily contains wires until GMF bug is fixed "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEdges" upperBound="-1"
        eType="#//WireEdge" eOpposite="#//WireEdge/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTrigger" eSuperTypes="#//NamedElement #//WireEdgesSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the source of events."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsEventTriggers" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTriggers" upperBound="-1"
        eType="#//EventTrigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" eSuperTypes="#//ApplicationElement #//ContainsWires #//wires/ParameterEdgesSource #//wires/ExtendsEdgesSource #//wires/ExtendsEdgeDestination">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.2 to extend the abstract counterpart&#xD;&#xA;0.3 to remove the abstract extension, and added &quot;type&quot; attribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a type of {@link DomainObjectInstance}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//DomainAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttribute" eSuperTypes="#//ApplicationElement #//ContainsWires #//wires/ParameterEdgesSource #//wires/ExtendsEdgesSource #//wires/ExtendsEdgeDestination">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.2 to extend the abstract counterpart&#xD;&#xA;0.3 to remove the abstract extension, and added &quot;type&quot; attribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a single attribute contained by a {@link DomainObject}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//GeneratedElement">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.4.2 to abstract"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//WireEdgeDestination #//NamedElement #//DataFlowEdgeDestination #//ExecutionEdgeDestination #//DataFlowEdgesSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents some type of executable step, which may contain logic flows, data flows or other operations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement #//DataFlowEdgesSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Incoming values to an {@link Operation operation} executed by a {@link RunInstanceWire} can be accessed via Parameters."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveOperation" eSuperTypes="#//Operation #//ExecutionEdgesSource #//WireEdgesSource">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="renamed from ChainedOperation -> PrimitiveOperation in 0.4"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Fundamental building blocks of application functionality. Their intent is based on their name."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeOperation" eSuperTypes="#//PrimitiveOperation #//ContainsOperations #//ContainsWires #//GeneratesElements #//ContainsConditions">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.2 added Scope supertype&#xD;&#xA;0.4 removed '_shouldnt_properties'&#xD;&#xA;0.4.2 removed Scope supertype"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Operations which are composed of logic flows, data flows, and other operations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataEdges" upperBound="-1"
        eType="#//DataFlowEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionEdges" upperBound="-1"
        eType="#//ExecutionEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//TemporaryVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StaticValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsOperations" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElement" eSuperTypes="#//ContainsOperations #//NamedElement #//ContainsEventTriggers #//WireEdgesSource #//WireEdgeDestination #//GeneratesElements #//ContainsConditions #//CanBeSynced">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="editor" value="org.openiaml.model.diagram.element"/>
      <details key="comment" value="Scope supertype added in 0.2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StaticValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElementContainer" abstract="true"
      eSuperTypes="#//ApplicationElement #//ContainsWires">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElementProperty" eSuperTypes="#//NamedElement #//WireEdgesSource #//WireEdgeDestination #//DataFlowEdgesSource #//DataFlowEdgeDestination #//wires/ParameterEdgesSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a single value, accessible and modifiable at runtime."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticValue" eSuperTypes="#//NamedElement #//WireEdgesSource #//DataFlowEdgesSource #//wires/ParameterEdgesSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a single value, which is accessible at runtime but can never change."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisibleThing" eSuperTypes="#//ContainsConditions #//ContainsEventTriggers #//ContainsOperations #//ContainsWires #//WireEdgesSource #//WireEdgeDestination #//NamedElement #//GeneratedElement #//GeneratesElements #//CanBeSynced #//wires/ParameterEdgesSource">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="this used to mean nothing; now anything that extends VisibleThing (which unforuntately needs to be concrete) has an editor"/>
      <details key="editor" value="org.openiaml.model.diagram.visual"/>
      <details key="changed" value="0.4.2 to no longer extend ApplicationElementContainer&#xD;&#xA;0.4.2 extends ContainsConditions&#xD;&#xA;0.4.2 extends ContainsOperatons&#xD;&#xA;0.4.2 extends ContainsEventTriggers&#xD;&#xA;0.4.2 extends ContainsWires&#xD;&#xA;0.4.2 extends WireEdgesSource&#xD;&#xA;0.4.2 extends WireEdgeDestination&#xD;&#xA;0.4.2 removed 'sessions' containment"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An abstract type representing application elements which have some sort of visible representation."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//VisibleThing" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StaticValue" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternetApplication" eSuperTypes="#//ContainsOperations #//ContainsEventTriggers #//NamedElement #//ContainsWires #//GeneratesElements #//ContainsConditions #//ContainsScopes">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="we cannot have InternetApplications inside of other ElementContainers, thus we don't define it as an ApplicationElement"/>
      <details key="comment2" value="but why can we have it as an ActivityEdgeSource? I don't think there are any examples of InternetApplication wire --> something else; all the wires are from objects INSIDE the IA"/>
      <details key="editor" value="org.openiaml.model.diagram"/>
      <details key="changed" value="0.4.2 no longer a Scope&#xD;&#xA;0.4.2 removed 'sessions' containment"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The top-level type of a model instance, representing all of the information required to define an Internet application."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainStores" upperBound="-1"
        eType="#//DomainStore" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="not sure if this is necessary anymore... because now objects are stored as part of their scopes"/>
        <details key="changed" value="0.2 to extend the abstract counterpart"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://localhost:8080/output/"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainStore" eSuperTypes="#//ContainsOperations #//ContainsEventTriggers #//NamedElement #//ContainsWires #//ContainsConditions #//GeneratesElements">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="editor" value="org.openiaml.model.diagram.domain_store"/>
      <details key="changed" value="0.2 to extend the abstract counterpart&#xD;&#xA;0.3 to remove the abstract extension, and added &quot;type&quot; attribute&#xD;&#xA;0.4.2 removed 'views' reference"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Stores many instances of {@link DomainObject DomainObjects} in some storage device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//DomainObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//DomainAttribute" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
        <details key="reason" value="why can a data store only contain tables? why can't they also contain single values?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1" eType="#//domain/FileReference">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
        <details key="comment" value="originally from FileDomainStore"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//domain/DomainStoreTypes">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowEdge" eSuperTypes="#//GeneratedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the flow of data from a {@link DataFlowEdgesSource data source} to a {@link DataFlowEdgeDestination data destination}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//DataFlowEdgesSource"
        eOpposite="#//DataFlowEdgesSource/outFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//DataFlowEdgeDestination"
        eOpposite="#//DataFlowEdgeDestination/inFlows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowEdgeDestination" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inFlows" upperBound="-1"
        eType="#//DataFlowEdge" eOpposite="#//DataFlowEdge/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowEdgesSource" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outFlows" upperBound="-1"
        eType="#//DataFlowEdge" eOpposite="#//DataFlowEdge/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporaryVariable" eSuperTypes="#//NamedElement #//DataFlowEdgesSource #//DataFlowEdgeDestination">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Temporary storage of values contained within an {@link Operation} which will be lost once the operation is completed."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEdge" eSuperTypes="#//GeneratedElement #//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the execution flow within an {@link Operation}."/>
    </eAnnotations>
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.4.1 to add NamedElement supertype"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//ExecutionEdgesSource"
        eOpposite="#//ExecutionEdgesSource/outExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//ExecutionEdgeDestination"
        eOpposite="#//ExecutionEdgeDestination/inExecutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEdgeDestination" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inExecutions" upperBound="-1"
        eType="#//ExecutionEdge" eOpposite="#//ExecutionEdge/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEdgesSource" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outExecutions" upperBound="-1"
        eType="#//ExecutionEdge" eOpposite="#//ExecutionEdge/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalEdge" eSuperTypes="#//ExecutionEdge #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicApplicationElementSet" eSuperTypes="#//ApplicationElement #//wires/ParameterEdgesSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsWires" abstract="true" interface="true">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.4.3 added 'parameterEdges' containment reference"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wires" upperBound="-1"
        eType="#//WireEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterEdges" upperBound="-1"
        eType="#//wires/ParameterEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsEdges" upperBound="-1"
        eType="#//wires/ExtendsEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiresEdges" upperBound="-1"
        eType="#//wires/RequiresEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providesEdges" upperBound="-1"
        eType="#//wires/ProvidesEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintEdges" upperBound="-1"
        eType="#//wires/ConstraintEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShouldntContainWires" abstract="true"
      interface="true" eSuperTypes="#//ContainsWires">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="classes that extend this SHOULDN'T contain wires, but GMF's limitations require it (see bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=249717)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedElement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A GeneratedElement may have been created manually, or initialised through model completion {@link GeneratesElements by another element}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" upperBound="-1"
        eType="#//GeneratesElements" eOpposite="#//GeneratesElements/generatedElements">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="changed" value="0.4 from 0..1 to 0..*"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isGenerated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.2. used to register the source of the rule that created this element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratesElements" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedElements" upperBound="-1"
        eType="#//GeneratedElement" eOpposite="#//GeneratedElement/generatedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObjectInstance" eSuperTypes="#//ApplicationElement #//ContainsWires #//wires/ParameterEdgesSource #//wires/ParameterEdgeDestination">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.2"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an instance of a {@link DomainObject}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//DomainAttributeInstance" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="changed" value="0.3: changed from DomainAttribute to DomainAttributeInstance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autosave" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
        <details key="changed" value="0.4.3 to default 'false' instead of 'true'"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true" eSuperTypes="#//GeneratesElements #//ContainsWires #//ContainsScopes #//NamedElement #//GeneratedElement #//WireEdgesSource #//WireEdgeDestination #//ContainsEventTriggers #//ContainsConditions #//CanBeSynced">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="changed" value="0.4: 'domainObjects', 'domainViews', 'domainInstances' references removed&#xD;&#xA;0.4.2: renamed from 'Scope' to 'AbstractScope'; added 'gate' reference"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryGate" eType="#//components/EntryGate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitGate" eType="#//components/ExitGate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StaticValue" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//QueryParameter" containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
        <details key="about" value="ideally this might only be placed in Page and Session, but allowing it within VisibleThing allows us to (1) reuse our visual editor, and (2) increases modularity of components perhaps?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" eSuperTypes="#//WireEdgesSource #//DataFlowEdgesSource #//NamedElement">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="added in 0.2"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Condition allows for conditional execution of {@link WireEdge wires} when {@link ConditionWire connected}."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeCondition" eSuperTypes="#//ContainsConditions #//Condition #//GeneratesElements #//ContainsOperations">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="added in 0.2&#xD;&#xA;_shouldnt_properties removed in 0.4&#xD;&#xA;ContainsOperations added in 0.4.1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A custom condition, composed in the same way as {@link CompositeOperation operations}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataEdges" upperBound="-1"
        eType="#//DataFlowEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionEdges" upperBound="-1"
        eType="#//ExecutionEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//TemporaryVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StaticValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsConditions" abstract="true"
      interface="true">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="added in 0.2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttributeInstance" eSuperTypes="#//ApplicationElement #//wires/ExtendsEdgesSource #//wires/ExtendsEdgeDestination">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.3"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an instance of a {@link DomainAttribute}, which is likely contained within a {@link DomainObjectInstance}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autosave" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
        <details key="changed" value="0.4.3 to default 'false' instead of 'true'"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParameter" eSuperTypes="#//NamedElement #//WireEdgesSource #//DataFlowEdgesSource #//wires/ParameterEdgesSource">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.4"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a query parameter from the browser's URI string."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsScopes" abstract="true" interface="true"
      eSuperTypes="#//ContainsOperations">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="added in 0.4.2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//Scope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanBeSynced" abstract="true" interface="true"
      eSuperTypes="#//NamedElement #//GeneratedElement #//GeneratesElements #//ContainsWires #//ContainsEventTriggers #//ContainsOperations #//ContainsConditions #//WireEdgesSource #//WireEdgeDestination"/>
  <eSubpackages name="visual" nsURI="http://openiaml.org/model/visual" nsPrefix="iaml.visual">
    <eClassifiers xsi:type="ecore:EClass" name="Frame" eSuperTypes="#//Scope #//wires/ParameterEdgesSource">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="Scope supertype added in 0.2"/>
        <details key="comment2" value="represents the scope Window"/>
        <details key="changed" value="0.4.2 renamed from Page to Frame&#xD;&#xA;0.4.2 no longer extends VisibleThing"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a single browser window instance."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//VisibleThing" containment="true">
        <eAnnotations source="http://openiaml.org/comment">
          <details key="added" value="0.4.2"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputForm" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a form which may contain {@link InputTextField text fields} and {@link Button buttons}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputTextField" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A single text field, storing a single text value, which may be edited by the user."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a clickable button to the user."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.3"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a static block of text that is not user-editable."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="wires" nsURI="http://openiaml.org/model/wires" nsPrefix="iaml.wires">
    <eClassifiers xsi:type="ecore:EClass" name="SingleWire" abstract="true" eSuperTypes="#//WireEdge">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="why do we have SingleWire at all? (following a design pattern?)"/>
        <details key="changed" value="0.4.2 to abstract"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeWire" eSuperTypes="#//WireEdge #//NamedElement #//ContainsWires #//GeneratesElements #//ContainsConditions">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="ideally this would be abstract; but we want to have a &quot;wire&quot; diagram editor, and the root element needs to be concrete. the other option is to have multiple diagram editors per concrete wire..."/>
        <details key="comment2" value="easy visualisation: all composite wires are dashed"/>
        <details key="comment3" value="only composite wires have a name now"/>
        <details key="editor" value="org.openiaml.model.diagram.wire"/>
        <details key="comment4" value="a wire shouldn't have parameters; but the operations contained within need them rendered."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//ApplicationElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//ApplicationElementProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventTriggers" upperBound="-1"
          eType="#//EventTrigger" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#//StaticValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SyncWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination #//wires/ParameterEdgeDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When a connected element changes, a SyncWire will update the other connected element."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunInstanceWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination #//wires/ParameterEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="RunWire: a composite wire that contains ExecutionWires/etc"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the execution of an {@link Operation}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://openiaml.org/comment">
          <details key="added" value="0.2"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterEdge" eSuperTypes="#//NamedElement #//GeneratedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Provides incoming values for {@link Parameter Parameters} of a {@link RunInstanceWire}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="changed" value="0.4.3 to no longer be a Wire; added 'from' and 'to' references; renamed to ParameterEdge"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://openiaml.org/comment">
          <details key="added" value="0.2"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//wires/ParameterEdgesSource" eOpposite="#//wires/ParameterEdgesSource/outParameterEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//wires/ParameterEdgeDestination"
          eOpposite="#//wires/ParameterEdgeDestination/inParameterEdges"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When the source element changes, the target element will be updated (but not vice versa)."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigateWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Executing this wire will navigate the user to the target {@link Page}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination #//wires/ParameterEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
        <details key="comment" value="parameters can be provided by ParameterWires"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allows for the selection of particular {@link DomainObjectInstance instances} from a {@link DomainStore}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination #//wires/ParameterEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When connected to a {@link RunInstanceWire}, the connected {@link Condition Conditions} will be evaluated before any execution takes place."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewInstanceWire" eSuperTypes="#//wires/CompositeWire">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Creates a new instance of a {@model DomainObjectInstance} or {@model DomainAttributeInstance} from its definition."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtendsEdge" eSuperTypes="#//GeneratedElement #//GeneratesElements">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
        <details key="changed" value="0.4.3 to no longer be a Wire; added 'from' and 'to' references; renamed to ExtendsEdge"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the inheritance of all target elements by the source element."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//wires/ExtendsEdgesSource" eOpposite="#//wires/ExtendsEdgesSource/outExtendsEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//wires/ExtendsEdgeDestination"
          eOpposite="#//wires/ExtendsEdgeDestination/inExtendsEdges"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiresEdge" eSuperTypes="#//GeneratedElement #//wires/ConstraintEdgesSource #//wires/ConstraintEdgeDestination #//ContainsWires">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
        <details key="changed" value="0.4.3 to no longer be a Wire; added 'from' and 'to' references; renamed to RequiresEdge"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the requirements for a {@link LoginHandler}, such as {@link Role Roles} and {@link Permission Permissions}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//users/RequiresEdgesSource" eOpposite="#//users/RequiresEdgesSource/outRequiresEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//users/RequiresEdgeDestination"
          eOpposite="#//users/RequiresEdgeDestination/inRequiresEdges"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintEdge" eSuperTypes="#//GeneratedElement">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
        <details key="changed" value="0.4.3 to no longer be a Wire; added 'from' and 'to' references; renamed to ConstraintEdge"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allows for the definition of complex {@model RequiresEdge requirements}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//wires/ConstraintEdgesSource" eOpposite="#//wires/ConstraintEdgesSource/outConstraintEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//wires/ConstraintEdgeDestination"
          eOpposite="#//wires/ConstraintEdgeDestination/inConstraintEdges"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//wires/ConstraintTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConstraintTypes">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
      </eAnnotations>
      <eLiterals name="AND"/>
      <eLiterals name="OR" value="1"/>
      <eLiterals name="XOR" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidesEdge" eSuperTypes="#//GeneratedElement">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
        <details key="changed" value="0.4.3 to no longer be a Wire; added 'from' and 'to' references; renamed to ProvidesEdge"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the source {@model Role} provides the target {@model Permission}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//users/ProvidesEdgesSource" eOpposite="#//users/ProvidesEdgesSource/outProvidesEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//users/ProvidesEdgeDestination"
          eOpposite="#//users/ProvidesEdgeDestination/inProvidesEdges"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterEdgesSource" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the source of a {@model ParameterEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outParameterEdges" upperBound="-1"
          eType="#//wires/ParameterEdge" eOpposite="#//wires/ParameterEdge/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterEdgeDestination" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the destination of a {@model ParameterEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inParameterEdges" upperBound="-1"
          eType="#//wires/ParameterEdge" eOpposite="#//wires/ParameterEdge/to"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtendsEdgesSource" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the source of a {@model ExtendsEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outExtendsEdges" upperBound="-1"
          eType="#//wires/ExtendsEdge" eOpposite="#//wires/ExtendsEdge/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtendsEdgeDestination" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the destination of a {@model ExtendsEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inExtendsEdges" upperBound="-1"
          eType="#//wires/ExtendsEdge" eOpposite="#//wires/ExtendsEdge/to"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintEdgesSource" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the source of a {@model ConstraintEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outConstraintEdges" upperBound="-1"
          eType="#//wires/ConstraintEdge" eOpposite="#//wires/ConstraintEdge/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintEdgeDestination" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the destination of a {@model ConstraintEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inConstraintEdges" upperBound="-1"
          eType="#//wires/ConstraintEdge" eOpposite="#//wires/ConstraintEdge/to"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="operations" nsURI="http://openiaml.org/model/operations" nsPrefix="iaml.operations">
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//ActivityNode #//ExecutionEdgesSource">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Start of an {@link CompositeOperation Operation} or {@link CompositeCondition Condition}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CancelNode" eSuperTypes="#//ActivityNode #//ExecutionEdgeDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the current {@link Operation} did not execute successfully, or the {@link Condition} failed."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FinishNode" eSuperTypes="#//ActivityNode #//ExecutionEdgeDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The successful completion of an {@link Operation}, or the {@link Condition} passed."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="#//ActivityNode #//ExecutionEdgesSource #//ExecutionEdgeDestination"/>
    <eClassifiers xsi:type="ecore:EClass" name="DecisionOperation" eSuperTypes="#//PrimitiveOperation #//DataFlowEdgeDestination"/>
    <eClassifiers xsi:type="ecore:EClass" name="DecisionCondition" eSuperTypes="#//Condition #//ExecutionEdgesSource #//ExecutionEdgeDestination #//DataFlowEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SplitNode" eSuperTypes="#//ActivityNode #//ExecutionEdgesSource #//ExecutionEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Execution flow can split off into multiple threads, reconnected with a {@link JoinNode}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="#//ActivityNode #//ExecutionEdgesSource #//ExecutionEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Joins multiple {@link SplitNode split} execution threads back together. Halts until all threads are complete."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallNode" eSuperTypes="#//ActivityNode #//ExecutionEdgesSource #//ExecutionEdgeDestination #//DataFlowEdgeDestination #//DataFlowEdgesSource #//WireEdgesSource #//NamedElement">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A virtual {@link Operation} call; the outgoing {@link RunInstanceWire} will be executed."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arithmetic" eSuperTypes="#//ActivityNode #//DataFlowEdgeDestination #//DataFlowEdgesSource">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.1"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An inline expression of arithmetic. Can be used as part of a {@link PrimitiveOperation set operation}, for example."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationType" eType="#//operations/ArithmeticOperationTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperationTypes">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.1"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the range of possible {@link ArithmeticOperation arithmetic operations}."/>
      </eAnnotations>
      <eLiterals name="ADD"/>
      <eLiterals name="SUBTRACT" value="1"/>
      <eLiterals name="MULTIPLY" value="2"/>
      <eLiterals name="DIVIDE" value="3"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="scopes" nsURI="http://openiaml.org/model/scopes" nsPrefix="iaml.scopes">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.2"/>
      <details key="comment" value="other scopes: iaml:InternetApplication, [...], iaml.visual:Page, iaml.visual:Frame, iaml:ApplicationElement, iaml:Operation"/>
      <details key="comment2" value="(it makes sense to put these scopes in here, because they are scoped in terms of visual terms)"/>
      <details key="comment3" value="some scopes aren't here: Host, Organisation, we can add these in later."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Session" eSuperTypes="#//NamedElement #//ContainsOperations #//Scope #//ContainsWires #//ContainsEventTriggers #//WireEdgesSource #//WireEdgeDestination #//ContainsConditions">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="changed" value="0.4: no longer extends VisibleThing; now extends ContainsEventTriggers, ContainsConditions, WireEdgesSource and WireEdgeDestination&#xD;&#xA;0.4.2 removed 'agents' reference"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a user session; contained data is normally not accessible by other users."/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="components" nsURI="http://openiaml.org/model/components" nsPrefix="iaml.components">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.2"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EEnum" name="LoginHandlerTypes">
      <eLiterals name="SECRET_KEY"/>
      <eLiterals name="DOMAIN_OBJECT" value="1"/>
      <eLiterals name="USER" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoginHandler" eSuperTypes="#//ApplicationElementContainer #//GeneratesElements #//wires/ParameterEdgeDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When placed into a {@link Page} or {@link Session}, enforces that users need to login via this LoginHandler first. Also supports logout."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//components/LoginHandlerTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessControlHandler" eSuperTypes="#//ApplicationElementContainer #//GeneratesElements #//wires/ParameterEdgeDestination #//users/RequiresEdgesSource #//users/ProvidesEdgesSource">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When placed into a {@link Page} or {@link Session}, enforces that all access contains the {@link Role roles} and {@link Permission permissions} provided by incoming {@link RequiresWire}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Gate" abstract="true" eSuperTypes="#//NamedElement #//WireEdgesSource #//WireEdgeDestination #//GeneratedElement #//GeneratesElements">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntryGate" eSuperTypes="#//components/Gate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When placed into a {@link Scope} (including {@link Session}), all {@link Page} accesses within that Scope must first execute this {@link Gate}. If all incoming {@link ConditionWire}s are true, then access to this {@link Scope} is denied until such time any {@link ConditionWire}s becomes false."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExitGate" eSuperTypes="#//components/Gate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When placed into a {@link Scope} (including {@link Session}), all {@link Page} accesses within that Scope must finally execute this {@link Gate}. If all incoming {@link ConditionWire}s are true, then access to this {@link Scope} is denied until such time any {@link ConditionWire}s becomes false."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.4.2"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="domain" nsURI="http://openiaml.org/model/domain" nsPrefix="iaml.domain">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.2"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EDataType" name="FileReference" instanceClassName="org.openiaml.model.FileReference"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DomainStoreTypes">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.3"/>
      </eAnnotations>
      <eLiterals name="RELATIONAL_DB"/>
      <eLiterals name="PROPERTIES_FILE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmptyDomainClass" abstract="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="this exists solely to ensure DomainProviderFactory is generated in .genmodel; otherwise GMF complains"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="users" nsURI="http://openiaml.org/model/users" nsPrefix="iaml.users">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="added" value="0.4"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="UserStore" eSuperTypes="#//DomainStore">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains {@link Role Roles} and {@link Permission Permissions}."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
          eType="#//users/Permission" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//DomainObject #//users/RequiresEdgeDestination #//users/ProvidesEdgesSource">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="note" value="another option is to create 'extends : Role' and 'extendedBy : Role' as EOpposites, and remove ExtendsWire. but this means that this relationship cannot be used as the target or source of any wires (parameters? conditions?)"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A particular Role that a user may have; may be {@link ExtendsWire inherited} from other Roles."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Permission" eSuperTypes="#//NamedElement #//WireEdgesSource #//WireEdgeDestination #//wires/ParameterEdgesSource #//users/RequiresEdgeDestination #//users/ProvidesEdgeDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A single Permission that a user may have; may also be {@link ProvidesWire provided} by a {@link Role}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserInstance" eSuperTypes="#//DomainObjectInstance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents {@link DomainObjectInstance an instance} of a {@link Role user}."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidesEdgesSource" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the source of a {@model ProvidesEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outProvidesEdges" upperBound="-1"
          eType="#//wires/ProvidesEdge" eOpposite="#//wires/ProvidesEdge/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidesEdgeDestination" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the destination of a {@model ProvidesEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inProvidesEdges" upperBound="-1"
          eType="#//wires/ProvidesEdge" eOpposite="#//wires/ProvidesEdge/to"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiresEdgesSource" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the source of a {@model RequiresEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outRequiresEdges" upperBound="-1"
          eType="#//wires/RequiresEdge" eOpposite="#//wires/RequiresEdge/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiresEdgeDestination" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Something which may be used as the destination of a {@model RequiresEdge}."/>
      </eAnnotations>
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="added in 0.4.3"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inRequiresEdges" upperBound="-1"
          eType="#//wires/RequiresEdge" eOpposite="#//wires/RequiresEdge/to"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
