<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://openiaml.org/model" nsPrefix="iaml">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//WireEdgesSource"
        eOpposite="#//WireEdgesSource/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//WireEdgeDestination"
        eOpposite="#//WireEdgeDestination/inEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgeDestination" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEdges" upperBound="-1"
        eType="#//WireEdge" eOpposite="#//WireEdge/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgesSource" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//WireEdge" containment="true" eOpposite="#//WireEdge/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTrigger" eSuperTypes="#//NamedElement #//WireEdgesSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsEventTriggers" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTriggers" upperBound="-1"
        eType="#//EventTrigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//DomainAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttribute" eSuperTypes="#//ApplicationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//WireEdgeDestination #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//OperationParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationParameter" eSuperTypes="#//NamedElement #//WireEdgeDestination"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleOperation" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChainedOperation" eSuperTypes="#//Operation #//WireEdgesSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subOperations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventAwareOperation" eSuperTypes="#//CompositeOperation #//ContainsEventTriggers"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsOperations" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElement" eSuperTypes="#//ContainsOperations #//NamedElement #//ContainsEventTriggers #//WireEdgesSource #//WireEdgeDestination">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="editor" value="org.openiaml.model.diagram.element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElementContainer" abstract="true"
      eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElementProperty" eSuperTypes="#//NamedElement #//WireEdgesSource #//WireEdgeDestination"/>
  <eClassifiers xsi:type="ecore:EClass" name="VisibleThing" eSuperTypes="#//ApplicationElementContainer">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="this used to mean nothing; now anything that extends VisibleThing (which unforuntately needs to be concrete) has an editor"/>
      <details key="editor" value="org.openiaml.model.diagram.visual"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternetApplication" eSuperTypes="#//ContainsOperations #//ContainsEventTriggers #//NamedElement">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="we cannot have InternetApplications inside of other ElementContainers, thus we don't define it as an ApplicationElement"/>
      <details key="comment2" value="but why can we have it as an ActivityEdgeSource? I don't think there are any examples of InternetApplication wire --> something else; all the wires are from objects INSIDE the IA"/>
      <details key="editor" value="org.openiaml.model.diagram"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainStores" upperBound="-1"
        eType="#//DomainStore" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainStore" eSuperTypes="#//ContainsOperations #//ContainsEventTriggers #//NamedElement">
    <eAnnotations source="http://openiaml.org/comment">
      <details key="comment" value="stores database objects"/>
      <details key="editor" value="org.openiaml.model.diagram.domain_store"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//DomainObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ApplicationElementProperty" containment="true"/>
  </eClassifiers>
  <eSubpackages name="visual" nsURI="http://openiaml.org/model/visual" nsPrefix="iaml.visual">
    <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//VisibleThing">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputForm" eSuperTypes="#//VisibleThing"/>
    <eClassifiers xsi:type="ecore:EClass" name="InputTextField" eSuperTypes="#//VisibleThing"/>
  </eSubpackages>
  <eSubpackages name="wires" nsURI="http://openiaml.org/model/wires" nsPrefix="iaml.wires">
    <eClassifiers xsi:type="ecore:EClass" name="SingleWire" eSuperTypes="#//WireEdge">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="ideally this would be abstract; but we want to have a &quot;wire&quot; diagram editor, and the root element needs to be concrete. the other option is to have multiple diagram editors per concrete wire..."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeWire" eSuperTypes="#//WireEdge #//NamedElement">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="ideally this would be abstract; but we want to have a &quot;wire&quot; diagram editor, and the root element needs to be concrete. the other option is to have multiple diagram editors per concrete wire..."/>
        <details key="comment2" value="easy visualisation: all composite wires are dashed"/>
        <details key="comment3" value="only composite wires have a name now"/>
        <details key="editor" value="org.openiaml.model.diagram.wire"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//ApplicationElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//ApplicationElementProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventTriggers" upperBound="-1"
          eType="#//EventTrigger" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SyncWire" eSuperTypes="#//wires/CompositeWire"/>
    <eClassifiers xsi:type="ecore:EClass" name="RunWire" eSuperTypes="#//wires/CompositeWire #//WireEdgeDestination">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="RunWire: a composite wire that contains ExecutionWires/etc"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionWire" eSuperTypes="#//wires/SingleWire"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedParameterWire" eSuperTypes="#//wires/SingleWire"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyToParameterWire" eSuperTypes="#//wires/SingleWire"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyToExecutionWire" eSuperTypes="#//wires/SingleWire"/>
  </eSubpackages>
  <eSubpackages name="operations" nsURI="http://openiaml.org/model/operations" nsPrefix="iaml.operations">
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//SingleOperation #//WireEdgesSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="#//SingleOperation"/>
    <eClassifiers xsi:type="ecore:EClass" name="FinishNode" eSuperTypes="#//SingleOperation"/>
    <eClassifiers xsi:type="ecore:EClass" name="SplitNode" eSuperTypes="#//SingleOperation #//WireEdgesSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="#//SingleOperation #//WireEdgesSource"/>
  </eSubpackages>
</ecore:EPackage>
