package org.openiaml.model.drools.rules.conditions

#list any import classes here.
import org.openiaml.model.drools.*;

import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global OverridableCreateElementsHelper handler;
global DroolsInsertionQueue queue;
global DroolsHelperFunctions functions;

# TODO can we put this function into something global?
function boolean connects(Wire wire, Object a, Object b) {
	return (wire.getFrom().equals(a) && wire.getTo().equals(b)) ||
		(wire.getFrom().equals(b) && wire.getTo().equals(a));
}

/**
 * TODO these rules should be refactored somehow.
 *
 * @inference SyncWire,ActionEdge,ConditionEdge 
 *		{@model ActionEdge ActionEdges} with incoming {@model ConditionEdge conditions} will be 
 *		copied to elements created by {@model SyncWire SyncWires}.
 */
rule "Connect ConditionEdges to ActionEdges created by SyncWires (edit/update) (onChange)"
	when
		# we have a sync wire
		source : Changeable( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )
		
		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )		
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

rule "Connect ConditionEdges to ActionEdges created by SyncWires (access/init) (onAccess)"
	when
		# we have a sync wire
		source : Accessible( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )

		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )		
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue )
		param : ParameterEdge ( from == fvalue, to == run ) 
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

/**
 * @inference SyncWire,ActionEdge,ConditionEdge,ParameterEdge 
 *		{@model ActionEdge ActionEdges} with incoming {@model ConditionEdge conditions} 
 *		with {@model ParameterEdge parameters} will be copied to elements 
 *		created by {@model SyncWire SyncWires}.
 */
rule "Connect ParameterEdges to ConditionEdges connected to ActionEdges created by SyncWires (edit/update) (onChange)"
	when
		# we have a syncwire
		source : Changeable( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )

		# that has created a ActionEdge
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the ActionEdge has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end

rule "Connect ParameterEdges to ConditionEdges connected to ActionEdges created by SyncWires (access/init) (onAccess)"
	when
		# we have a syncwire
		source : Accessible( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )

		# that has created a ActionEdge
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )

		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue ) 
		param2 : ParameterEdge ( from == fvalue, to == run ) 

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the ActionEdge has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end

/**
 * @inference SetWire,ActionEdge,ConditionEdge 
 *		{@model ActionEdge ActionEdges} with incoming {@model ConditionEdge conditions} will be 
 *		copied to elements created by {@model SetWire}s.
 */
rule "Connect ConditionEdges to ActionEdges created by SetWires (edit/update) (onChange)"
	when
		# we have a sync wire
		source : Changeable( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )

		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )		
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

rule "Connect ConditionEdges to ActionEdges created by SetWires (access/init) (onAccess)"
	when
		# we have a sync wire
		source : Accessible( )
		target : ContainsOperations( )
		sw : SyncWire( (from == source && to == target) || (from == target && to == source) )

		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )		
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue )
		param : ParameterEdge ( from == fvalue, to == run ) 
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

/**
 * @inference SetWire,ActionEdge,ConditionEdge,ParameterEdge 
 *		{@model ActionEdge ActionEdges} with incoming {@model ConditionEdge conditions} 
 *		with {@model ParameterEdge parameters} will be copied to elements 
 *		created by {@model SetWire}s.
 */
rule "Connect ParameterEdges to ConditionEdges connected to ActionEdges created by SetWires (edit/update) (onChange)"
	when
		# we have a syncwire
		source : Changeable( )
		target : ContainsOperations( )
		sw : SetWire( from == source, to == target )
		
		# that has created a ActionEdge
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the ActionEdge has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end

rule "Connect ParameterEdges to ConditionEdges connected to ActionEdges created by SetWires (access/init) (onAccess)"
	when
		# we have a syncwire
		source : Accessible( )
		target : ContainsOperations( )
		sw : SetWire( from == source, to == target )

		# that has created a ActionEdge
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )
		run : ActionEdge( eContainer == sw, from == event, to == operation, name == "run" )

		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue ) 
		param2 : ParameterEdge ( from == fvalue, to == run ) 

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the ActionEdge has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end
