<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iaml"
    nsURI="http://openiaml.org/iaml.test" nsPrefix="iaml">
  <eClassifiers xsi:type="ecore:EClass" name="InternetApplication" eSuperTypes="#//GeneratedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" eSuperTypes="#//GeneratedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Editor" abstract="true" eSuperTypes="#//GeneratedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" upperBound="-1" eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checkbox" eSuperTypes="#//Editor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//GeneratedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//Editor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" eType="#//GeneratedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isGenerated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
