#created on: 4/11/2008
package org.openiaml.model.drools.rules.events

#list any import classes here.
import org.openiaml.model.drools.*;

import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global OverridableCreateElementsHelper handler;
global DroolsInsertionQueue queue;
global DroolsHelperFunctions functions;

/**
 * @inference Changeable,DomainAttribute 
 *		A {@model Changeable} thing contains an {@model EventTrigger} named 'onChange'. 
 */
rule "Create 'onChange' event trigger for Changeable things"
	when
		f : Changeable( )
		g : GeneratesElements ( overridden == false, eval(f == g) )
		not (event : EventTrigger( f.onChange == event ))

	then
		EventTrigger event = handler.generatedEventTriggerOnChange(g, f);
		queue.add(event, drools);
		
end

/**
 * @inference Accessible
 *		An {@model Accessible} thing contains an {@model EventTrigger} named 'onAccess'.
 */
rule "Create 'onAccess' event trigger for Accessible things"
	when
		f : Accessible( )
		g : GeneratesElements ( overridden == false, eval(f == g) )
		not (event : EventTrigger( f.onAccess == event ))

	then
		handler.veto(g);
		EventTrigger event = handler.generatedEventTriggerOnAccess(g, f);
		queue.add(event, drools);
		
end
