/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openiaml.model.model.domain.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.EObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.openiaml.model.model.ApplicationElementProperty;
import org.openiaml.model.model.ContainsEventTriggers;
import org.openiaml.model.model.ContainsWires;
import org.openiaml.model.model.DerivedView;
import org.openiaml.model.model.EventTrigger;
import org.openiaml.model.model.GeneratedElement;
import org.openiaml.model.model.GeneratesElements;
import org.openiaml.model.model.ModelPackage;
import org.openiaml.model.model.NamedElement;
import org.openiaml.model.model.Operation;
import org.openiaml.model.model.WireEdge;

import org.openiaml.model.model.domain.AbstractDomainAttribute;
import org.openiaml.model.model.domain.AbstractDomainObject;
import org.openiaml.model.model.domain.AbstractDomainStore;
import org.openiaml.model.model.domain.DomainPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Domain Store</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getOperations <em>Operations</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getEventTriggers <em>Event Triggers</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#isIsGenerated <em>Is Generated</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getGeneratedRule <em>Generated Rule</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getWires <em>Wires</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getGeneratedElements <em>Generated Elements</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#isOverridden <em>Overridden</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getChildren <em>Children</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getViews <em>Views</em>}</li>
 *   <li>{@link org.openiaml.model.model.domain.impl.AbstractDomainStoreImpl#getAttributes <em>Attributes</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public abstract class AbstractDomainStoreImpl extends EObjectImpl implements AbstractDomainStore {
	/**
	 * The cached value of the '{@link #getOperations() <em>Operations</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOperations()
	 * @generated
	 * @ordered
	 */
	protected EList<Operation> operations;

	/**
	 * The cached value of the '{@link #getEventTriggers() <em>Event Triggers</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEventTriggers()
	 * @generated
	 * @ordered
	 */
	protected EList<EventTrigger> eventTriggers;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected GeneratesElements generatedBy;

	/**
	 * The default value of the '{@link #isIsGenerated() <em>Is Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isIsGenerated()
	 * @generated
	 * @ordered
	 */
	protected static final boolean IS_GENERATED_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isIsGenerated() <em>Is Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isIsGenerated()
	 * @generated
	 * @ordered
	 */
	protected boolean isGenerated = IS_GENERATED_EDEFAULT;

	/**
	 * The default value of the '{@link #getId() <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getId()
	 * @generated
	 * @ordered
	 */
	protected static final String ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getId()
	 * @generated
	 * @ordered
	 */
	protected String id = ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedRule() <em>Generated Rule</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedRule()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_RULE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedRule() <em>Generated Rule</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedRule()
	 * @generated
	 * @ordered
	 */
	protected String generatedRule = GENERATED_RULE_EDEFAULT;

	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The cached value of the '{@link #getWires() <em>Wires</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getWires()
	 * @generated
	 * @ordered
	 */
	protected EList<WireEdge> wires;

	/**
	 * The cached value of the '{@link #getGeneratedElements() <em>Generated Elements</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedElements()
	 * @generated
	 * @ordered
	 */
	protected EList<GeneratedElement> generatedElements;

	/**
	 * The default value of the '{@link #isOverridden() <em>Overridden</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isOverridden()
	 * @generated
	 * @ordered
	 */
	protected static final boolean OVERRIDDEN_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isOverridden() <em>Overridden</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isOverridden()
	 * @generated
	 * @ordered
	 */
	protected boolean overridden = OVERRIDDEN_EDEFAULT;

	/**
	 * The cached value of the '{@link #getChildren() <em>Children</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getChildren()
	 * @generated
	 * @ordered
	 */
	protected EList<AbstractDomainObject> children;

	/**
	 * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getProperties()
	 * @generated
	 * @ordered
	 */
	protected EList<ApplicationElementProperty> properties;

	/**
	 * The cached value of the '{@link #getViews() <em>Views</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getViews()
	 * @generated
	 * @ordered
	 */
	protected EList<DerivedView> views;

	/**
	 * The cached value of the '{@link #getAttributes() <em>Attributes</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAttributes()
	 * @generated
	 * @ordered
	 */
	protected EList<AbstractDomainAttribute> attributes;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractDomainStoreImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return DomainPackage.Literals.ABSTRACT_DOMAIN_STORE;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Operation> getOperations() {
		if (operations == null) {
			operations = new EObjectContainmentEList<Operation>(Operation.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS);
		}
		return operations;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<EventTrigger> getEventTriggers() {
		if (eventTriggers == null) {
			eventTriggers = new EObjectContainmentEList<EventTrigger>(EventTrigger.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS);
		}
		return eventTriggers;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GeneratesElements getGeneratedBy() {
		if (generatedBy != null && generatedBy.eIsProxy()) {
			InternalEObject oldGeneratedBy = (InternalEObject)generatedBy;
			generatedBy = (GeneratesElements)eResolveProxy(oldGeneratedBy);
			if (generatedBy != oldGeneratedBy) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY, oldGeneratedBy, generatedBy));
			}
		}
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GeneratesElements basicGetGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetGeneratedBy(GeneratesElements newGeneratedBy, NotificationChain msgs) {
		GeneratesElements oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY, oldGeneratedBy, newGeneratedBy);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGeneratedBy(GeneratesElements newGeneratedBy) {
		if (newGeneratedBy != generatedBy) {
			NotificationChain msgs = null;
			if (generatedBy != null)
				msgs = ((InternalEObject)generatedBy).eInverseRemove(this, ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS, GeneratesElements.class, msgs);
			if (newGeneratedBy != null)
				msgs = ((InternalEObject)newGeneratedBy).eInverseAdd(this, ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS, GeneratesElements.class, msgs);
			msgs = basicSetGeneratedBy(newGeneratedBy, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY, newGeneratedBy, newGeneratedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isIsGenerated() {
		return isGenerated;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setIsGenerated(boolean newIsGenerated) {
		boolean oldIsGenerated = isGenerated;
		isGenerated = newIsGenerated;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED, oldIsGenerated, isGenerated));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setId(String newId) {
		String oldId = id;
		id = newId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__ID, oldId, id));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getGeneratedRule() {
		return generatedRule;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGeneratedRule(String newGeneratedRule) {
		String oldGeneratedRule = generatedRule;
		generatedRule = newGeneratedRule;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE, oldGeneratedRule, generatedRule));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<WireEdge> getWires() {
		if (wires == null) {
			wires = new EObjectContainmentEList<WireEdge>(WireEdge.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES);
		}
		return wires;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<GeneratedElement> getGeneratedElements() {
		if (generatedElements == null) {
			generatedElements = new EObjectWithInverseResolvingEList<GeneratedElement>(GeneratedElement.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS, ModelPackage.GENERATED_ELEMENT__GENERATED_BY);
		}
		return generatedElements;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isOverridden() {
		return overridden;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOverridden(boolean newOverridden) {
		boolean oldOverridden = overridden;
		overridden = newOverridden;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN, oldOverridden, overridden));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<AbstractDomainObject> getChildren() {
		if (children == null) {
			children = new EObjectContainmentEList<AbstractDomainObject>(AbstractDomainObject.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN);
		}
		return children;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ApplicationElementProperty> getProperties() {
		if (properties == null) {
			properties = new EObjectContainmentEList<ApplicationElementProperty>(ApplicationElementProperty.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES);
		}
		return properties;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<DerivedView> getViews() {
		if (views == null) {
			views = new EObjectResolvingEList<DerivedView>(DerivedView.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__VIEWS);
		}
		return views;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<AbstractDomainAttribute> getAttributes() {
		if (attributes == null) {
			attributes = new EObjectContainmentEList<AbstractDomainAttribute>(AbstractDomainAttribute.class, this, DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES);
		}
		return attributes;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				if (generatedBy != null)
					msgs = ((InternalEObject)generatedBy).eInverseRemove(this, ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS, GeneratesElements.class, msgs);
				return basicSetGeneratedBy((GeneratesElements)otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getGeneratedElements()).basicAdd(otherEnd, msgs);
		}
		return super.eInverseAdd(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS:
				return ((InternalEList<?>)getOperations()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS:
				return ((InternalEList<?>)getEventTriggers()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				return basicSetGeneratedBy(null, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES:
				return ((InternalEList<?>)getWires()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				return ((InternalEList<?>)getGeneratedElements()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN:
				return ((InternalEList<?>)getChildren()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES:
				return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES:
				return ((InternalEList<?>)getAttributes()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS:
				return getOperations();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS:
				return getEventTriggers();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				if (resolve) return getGeneratedBy();
				return basicGetGeneratedBy();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED:
				return isIsGenerated() ? Boolean.TRUE : Boolean.FALSE;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ID:
				return getId();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE:
				return getGeneratedRule();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__NAME:
				return getName();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES:
				return getWires();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				return getGeneratedElements();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN:
				return isOverridden() ? Boolean.TRUE : Boolean.FALSE;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN:
				return getChildren();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES:
				return getProperties();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__VIEWS:
				return getViews();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES:
				return getAttributes();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS:
				getOperations().clear();
				getOperations().addAll((Collection<? extends Operation>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS:
				getEventTriggers().clear();
				getEventTriggers().addAll((Collection<? extends EventTrigger>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				setGeneratedBy((GeneratesElements)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED:
				setIsGenerated(((Boolean)newValue).booleanValue());
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ID:
				setId((String)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE:
				setGeneratedRule((String)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__NAME:
				setName((String)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES:
				getWires().clear();
				getWires().addAll((Collection<? extends WireEdge>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				getGeneratedElements().clear();
				getGeneratedElements().addAll((Collection<? extends GeneratedElement>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN:
				setOverridden(((Boolean)newValue).booleanValue());
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN:
				getChildren().clear();
				getChildren().addAll((Collection<? extends AbstractDomainObject>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES:
				getProperties().clear();
				getProperties().addAll((Collection<? extends ApplicationElementProperty>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__VIEWS:
				getViews().clear();
				getViews().addAll((Collection<? extends DerivedView>)newValue);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES:
				getAttributes().clear();
				getAttributes().addAll((Collection<? extends AbstractDomainAttribute>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS:
				getOperations().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS:
				getEventTriggers().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				setGeneratedBy((GeneratesElements)null);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED:
				setIsGenerated(IS_GENERATED_EDEFAULT);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ID:
				setId(ID_EDEFAULT);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE:
				setGeneratedRule(GENERATED_RULE_EDEFAULT);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__NAME:
				setName(NAME_EDEFAULT);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES:
				getWires().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				getGeneratedElements().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN:
				setOverridden(OVERRIDDEN_EDEFAULT);
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN:
				getChildren().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES:
				getProperties().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__VIEWS:
				getViews().clear();
				return;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES:
				getAttributes().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OPERATIONS:
				return operations != null && !operations.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS:
				return eventTriggers != null && !eventTriggers.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY:
				return generatedBy != null;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED:
				return isGenerated != IS_GENERATED_EDEFAULT;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ID:
				return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE:
				return GENERATED_RULE_EDEFAULT == null ? generatedRule != null : !GENERATED_RULE_EDEFAULT.equals(generatedRule);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES:
				return wires != null && !wires.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS:
				return generatedElements != null && !generatedElements.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN:
				return overridden != OVERRIDDEN_EDEFAULT;
			case DomainPackage.ABSTRACT_DOMAIN_STORE__CHILDREN:
				return children != null && !children.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__PROPERTIES:
				return properties != null && !properties.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__VIEWS:
				return views != null && !views.isEmpty();
			case DomainPackage.ABSTRACT_DOMAIN_STORE__ATTRIBUTES:
				return attributes != null && !attributes.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass) {
		if (baseClass == ContainsEventTriggers.class) {
			switch (derivedFeatureID) {
				case DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS: return ModelPackage.CONTAINS_EVENT_TRIGGERS__EVENT_TRIGGERS;
				default: return -1;
			}
		}
		if (baseClass == GeneratedElement.class) {
			switch (derivedFeatureID) {
				case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY: return ModelPackage.GENERATED_ELEMENT__GENERATED_BY;
				case DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED: return ModelPackage.GENERATED_ELEMENT__IS_GENERATED;
				case DomainPackage.ABSTRACT_DOMAIN_STORE__ID: return ModelPackage.GENERATED_ELEMENT__ID;
				case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE: return ModelPackage.GENERATED_ELEMENT__GENERATED_RULE;
				default: return -1;
			}
		}
		if (baseClass == NamedElement.class) {
			switch (derivedFeatureID) {
				case DomainPackage.ABSTRACT_DOMAIN_STORE__NAME: return ModelPackage.NAMED_ELEMENT__NAME;
				default: return -1;
			}
		}
		if (baseClass == ContainsWires.class) {
			switch (derivedFeatureID) {
				case DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES: return ModelPackage.CONTAINS_WIRES__WIRES;
				default: return -1;
			}
		}
		if (baseClass == GeneratesElements.class) {
			switch (derivedFeatureID) {
				case DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS: return ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS;
				case DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN: return ModelPackage.GENERATES_ELEMENTS__OVERRIDDEN;
				default: return -1;
			}
		}
		return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass) {
		if (baseClass == ContainsEventTriggers.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_EVENT_TRIGGERS__EVENT_TRIGGERS: return DomainPackage.ABSTRACT_DOMAIN_STORE__EVENT_TRIGGERS;
				default: return -1;
			}
		}
		if (baseClass == GeneratedElement.class) {
			switch (baseFeatureID) {
				case ModelPackage.GENERATED_ELEMENT__GENERATED_BY: return DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_BY;
				case ModelPackage.GENERATED_ELEMENT__IS_GENERATED: return DomainPackage.ABSTRACT_DOMAIN_STORE__IS_GENERATED;
				case ModelPackage.GENERATED_ELEMENT__ID: return DomainPackage.ABSTRACT_DOMAIN_STORE__ID;
				case ModelPackage.GENERATED_ELEMENT__GENERATED_RULE: return DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_RULE;
				default: return -1;
			}
		}
		if (baseClass == NamedElement.class) {
			switch (baseFeatureID) {
				case ModelPackage.NAMED_ELEMENT__NAME: return DomainPackage.ABSTRACT_DOMAIN_STORE__NAME;
				default: return -1;
			}
		}
		if (baseClass == ContainsWires.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_WIRES__WIRES: return DomainPackage.ABSTRACT_DOMAIN_STORE__WIRES;
				default: return -1;
			}
		}
		if (baseClass == GeneratesElements.class) {
			switch (baseFeatureID) {
				case ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS: return DomainPackage.ABSTRACT_DOMAIN_STORE__GENERATED_ELEMENTS;
				case ModelPackage.GENERATES_ELEMENTS__OVERRIDDEN: return DomainPackage.ABSTRACT_DOMAIN_STORE__OVERRIDDEN;
				default: return -1;
			}
		}
		return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuffer result = new StringBuffer(super.toString());
		result.append(" (isGenerated: ");
		result.append(isGenerated);
		result.append(", id: ");
		result.append(id);
		result.append(", generatedRule: ");
		result.append(generatedRule);
		result.append(", name: ");
		result.append(name);
		result.append(", overridden: ");
		result.append(overridden);
		result.append(')');
		return result.toString();
	}

} //AbstractDomainStoreImpl
