package iaml.generated2;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Tue Oct 28 12:15:47 NZDT 2008
 */
@SuppressWarnings("unchecked")
class KBFragement_getApplicationChildren {
    /**
     * Method generated for query /generated_app_children[in,out]
     * @param app input parameter generated from slot 0
     * @return an iterator for instances of GeneratedAppChildren
    */
    public static ResultSet<GeneratedAppChildren> getApplicationChildren(
        final org.openiaml.model.model.InternetApplication app) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<GeneratedAppChildren> _result = new ResultSet(KBFragement_getApplicationChildren.getApplicationChildren(
                    app, _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query /generated_app_children[in,out]
     * @param app input parameter generated from slot 0
     * @return an iterator for instances of GeneratedAppChildren
    */
    static ResourceIterator<GeneratedAppChildren> getApplicationChildren(
        final org.openiaml.model.model.InternetApplication app,
        final DerivationController _derivation) {
        final int _derivationlevel = _derivation.getDepth();
        ResourceIterator<GeneratedAppChildren> result = new IteratorChain<GeneratedAppChildren>(1) {
                public Object getIteratorOrObject(int pos) {
                    switch (pos) {
                    // rule_test  IF /app_name([app],test) THEN /generated_app_children([app],[page_wrapper])
                    case 0:
                        return getApplicationChildren_0(app,
                            _derivation.reset(_derivationlevel));

                    default:
                        return EmptyIterator.DEFAULT;
                    } // switch(pos)
                } // getIterator()

                public String getRuleRef(int pos) {
                    switch (pos) {
                    // rule_test  IF /app_name([app],test) THEN /generated_app_children([app],[page_wrapper])
                    case 0:
                        return "rule_test";

                    default:
                        return "";
                    } // switch(pos)
                } // getRuleRef()
            };

        return result;
    }

    /**
     * Method generated for query /generated_app_children[in,out]
     * @param app input parameter generated from slot 0
     * @return an iterator for instances of GeneratedAppChildren
    */
    private static ResourceIterator<GeneratedAppChildren> getApplicationChildren_0(
        final org.openiaml.model.model.InternetApplication app,
        final DerivationController _derivation) {
        _derivation.log("rule_test", DerivationController.RULE, app,
            DerivationController.NIL);

        // comparing constants in rule head with parameters
        if (!Constants.app.equals(app)) {
            return EmptyIterator.DEFAULT;
        }

        // Variable bindings in rule:  IF /app_name([app],test) THEN /generated_app_children([app],[page_wrapper])
        class bindingsInRule1 {
            // Property generated for term  "test"
            java.lang.String p1;

            // Property generated for term  "[app]"
            org.openiaml.model.model.InternetApplication p2;

            // Property generated for term  "[page_wrapper]"
            org.openiaml.model.take.tests.PageWrapper p3;
        }
        ;

        final bindingsInRule1 bindings = new bindingsInRule1();
        bindings.p2 = Constants.app;
        bindings.p1 = "test";
        bindings.p3 = Constants.page_wrapper;

        // code for prereq /app_name([app],test)
        final ResourceIterator<InternetApplication_Name> iterator1 = KBFragement_getAppName.getAppName(Constants.app,
                "test", _derivation.increaseDepth());

        // code for prereq /generated_app_children([app],[page_wrapper])
        final ResourceIterator<GeneratedAppChildren> iterator2 = new NestedIterator<InternetApplication_Name, GeneratedAppChildren>(iterator1) {
                public ResourceIterator<GeneratedAppChildren> getNextIterator(
                    InternetApplication_Name object) {
                    bindings.p2 = Constants.app;
                    bindings.p1 = "test";

                    return new SingletonIterator(new GeneratedAppChildren(
                            bindings.p2, bindings.p3));
                }
            };

        return iterator2;
    }
}
