package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate element_children
 * @version Tue Oct 14 11:48:58 NZDT 2008
 */
public class ApplicationElementContainer_Children {
    public org.openiaml.model.diagram.custom.takeproxy.ApplicationElementContainerProxy slot1;
    public org.openiaml.model.diagram.custom.takeproxy.ApplicationElementProxy slot2;

    public ApplicationElementContainer_Children(
        org.openiaml.model.diagram.custom.takeproxy.ApplicationElementContainerProxy slot1,
        org.openiaml.model.diagram.custom.takeproxy.ApplicationElementProxy slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public ApplicationElementContainer_Children() {
        super();
    }
}
