package iaml.generated2;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Tue Oct 14 23:16:03 NZDT 2008
 */
@SuppressWarnings("unchecked")
public class Constants{
public static org.openiaml.model.model.InternetApplication app;
}
