package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store facts1
 * for the predicate name
 * @version Tue Oct 14 11:48:58 NZDT 2008
 */
public interface ExternalFactStore4NamedElement_Name {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<iaml.generated2.NamedElement_Name> fetch(
        org.openiaml.model.diagram.custom.takeproxy.NamedElementProxy element,
        java.lang.String string);
}
