package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate generated_or_input_form_name
 * @version Wed Oct 15 12:35:49 NZDT 2008
 */
public class generated_or_input_form_name {
    public org.openiaml.model.model.visual.InputForm slot1;
    public java.lang.String slot2;

    public generated_or_input_form_name(
        org.openiaml.model.model.visual.InputForm slot1, java.lang.String slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public generated_or_input_form_name() {
        super();
    }

    public String toString() {
        return "generated_or_input_form_name[slot1=" + slot1 + ", slot2=" +
        slot2 + "]";
    }

    //test4
}
