package iaml.generated2;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Wed Oct 15 12:20:07 NZDT 2008
 */
@SuppressWarnings("unchecked")
class KBFragement_getElementNames {
    /**
     * Method generated for query /input_form_name[out,out]
     * @return an iterator for instances of NamedElement_Name
    */
    public static ResultSet<NamedElement_Name> getElementNames() {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<NamedElement_Name> _result = new ResultSet(KBFragement_getElementNames.getElementNames(
                    _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query /input_form_name[out,out]
     * @return an iterator for instances of NamedElement_Name
    */
    static ResourceIterator<NamedElement_Name> getElementNames(
        final DerivationController _derivation) {
        final int _derivationlevel = _derivation.getDepth();
        ResourceIterator<NamedElement_Name> result = new IteratorChain<NamedElement_Name>(1) {
                public Object getIteratorOrObject(int pos) {
                    switch (pos) {
                    // factsInputForm_Name nz.org.take.ExternalFactStore@bad8a8
                    case 0:
                        return getElementNames_0(_derivation.reset(
                                _derivationlevel));

                    default:
                        return EmptyIterator.DEFAULT;
                    } // switch(pos)
                } // getIterator()

                public String getRuleRef(int pos) {
                    switch (pos) {
                    // factsInputForm_Name nz.org.take.ExternalFactStore@bad8a8
                    case 0:
                        return "factsInputForm_Name";

                    default:
                        return "";
                    } // switch(pos)
                } // getRuleRef()
            };

        return result;
    }

    /**
     * Method generated for query /input_form_name[out,out]
     * @return an iterator for instances of NamedElement_Name
    */
    private static ResourceIterator<NamedElement_Name> getElementNames_0(
        final DerivationController _derivation) {
        _derivation.log("factsInputForm_Name",
            DerivationController.EXTERNAL_FACT_SET, DerivationController.NIL,
            DerivationController.NIL);

        return FactStores.factsInputForm_Name.fetch(null, null);
    }
}
