package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate name
 * @version Tue Oct 14 11:48:58 NZDT 2008
 */
public class NamedElement_Name {
    public org.openiaml.model.diagram.custom.takeproxy.NamedElementProxy element;
    public java.lang.String string;

    public NamedElement_Name(
        org.openiaml.model.diagram.custom.takeproxy.NamedElementProxy element,
        java.lang.String string) {
        super();
        this.element = element;
        this.string = string;
    }

    public NamedElement_Name() {
        super();
    }
}
