/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openiaml.model.model.operations;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.openiaml.model.model.ModelPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.openiaml.model.model.operations.OperationsFactory
 * @model kind="package"
 * @generated
 */
public interface OperationsPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "operations";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://openiaml.org/model/operations";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "iaml.operations";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	OperationsPackage eINSTANCE = org.openiaml.model.model.operations.impl.OperationsPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.StartNodeImpl <em>Start Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.StartNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getStartNode()
	 * @generated
	 */
	int START_NODE = 0;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE__OUT_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Start Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int START_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.CancelNodeImpl <em>Cancel Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.CancelNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getCancelNode()
	 * @generated
	 */
	int CANCEL_NODE = 1;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Exception Text</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE__EXCEPTION_TEXT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Cancel Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CANCEL_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.FinishNodeImpl <em>Finish Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.FinishNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getFinishNode()
	 * @generated
	 */
	int FINISH_NODE = 2;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Finish Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINISH_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.DecisionNodeImpl <em>Decision Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.DecisionNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionNode()
	 * @generated
	 */
	int DECISION_NODE = 3;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__OUT_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Decision Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.DecisionOperationImpl <em>Decision Operation</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.DecisionOperationImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionOperation()
	 * @generated
	 */
	int DECISION_OPERATION = 4;

	/**
	 * The feature id for the '<em><b>In Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__IN_EDGES = ModelPackage.PRIMITIVE_OPERATION__IN_EDGES;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__GENERATED_BY = ModelPackage.PRIMITIVE_OPERATION__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__IS_GENERATED = ModelPackage.PRIMITIVE_OPERATION__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__ID = ModelPackage.PRIMITIVE_OPERATION__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__GENERATED_RULE = ModelPackage.PRIMITIVE_OPERATION__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__NAME = ModelPackage.PRIMITIVE_OPERATION__NAME;

	/**
	 * The feature id for the '<em><b>In Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__IN_FLOWS = ModelPackage.PRIMITIVE_OPERATION__IN_FLOWS;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__IN_EXECUTIONS = ModelPackage.PRIMITIVE_OPERATION__IN_EXECUTIONS;

	/**
	 * The feature id for the '<em><b>Out Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__OUT_FLOWS = ModelPackage.PRIMITIVE_OPERATION__OUT_FLOWS;

	/**
	 * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__PARAMETERS = ModelPackage.PRIMITIVE_OPERATION__PARAMETERS;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__OUT_EXECUTIONS = ModelPackage.PRIMITIVE_OPERATION__OUT_EXECUTIONS;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__WIRES = ModelPackage.PRIMITIVE_OPERATION__WIRES;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION__OUT_EDGES = ModelPackage.PRIMITIVE_OPERATION__OUT_EDGES;

	/**
	 * The number of structural features of the '<em>Decision Operation</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_OPERATION_FEATURE_COUNT = ModelPackage.PRIMITIVE_OPERATION_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.DecisionConditionImpl <em>Decision Condition</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.DecisionConditionImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionCondition()
	 * @generated
	 */
	int DECISION_CONDITION = 5;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__WIRES = ModelPackage.CONDITION__WIRES;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__OUT_EDGES = ModelPackage.CONDITION__OUT_EDGES;

	/**
	 * The feature id for the '<em><b>Out Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__OUT_FLOWS = ModelPackage.CONDITION__OUT_FLOWS;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__GENERATED_BY = ModelPackage.CONDITION__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__IS_GENERATED = ModelPackage.CONDITION__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__ID = ModelPackage.CONDITION__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__GENERATED_RULE = ModelPackage.CONDITION__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__NAME = ModelPackage.CONDITION__NAME;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__OUT_EXECUTIONS = ModelPackage.CONDITION_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__IN_EXECUTIONS = ModelPackage.CONDITION_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>In Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION__IN_FLOWS = ModelPackage.CONDITION_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Decision Condition</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DECISION_CONDITION_FEATURE_COUNT = ModelPackage.CONDITION_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.SplitNodeImpl <em>Split Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.SplitNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getSplitNode()
	 * @generated
	 */
	int SPLIT_NODE = 6;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__OUT_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Split Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPLIT_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.JoinNodeImpl <em>Join Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.JoinNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getJoinNode()
	 * @generated
	 */
	int JOIN_NODE = 7;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__OUT_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Join Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOIN_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.operations.impl.OperationCallNodeImpl <em>Operation Call Node</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.operations.impl.OperationCallNodeImpl
	 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getOperationCallNode()
	 * @generated
	 */
	int OPERATION_CALL_NODE = 8;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__GENERATED_BY = ModelPackage.ACTIVITY_NODE__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__IS_GENERATED = ModelPackage.ACTIVITY_NODE__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__ID = ModelPackage.ACTIVITY_NODE__ID;

	/**
	 * The feature id for the '<em><b>Generated Rule</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__GENERATED_RULE = ModelPackage.ACTIVITY_NODE__GENERATED_RULE;

	/**
	 * The feature id for the '<em><b>Out Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__OUT_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>In Executions</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__IN_EXECUTIONS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>In Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__IN_FLOWS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Out Flows</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__OUT_FLOWS = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 3;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__WIRES = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 4;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__OUT_EDGES = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 5;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE__NAME = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 6;

	/**
	 * The number of structural features of the '<em>Operation Call Node</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPERATION_CALL_NODE_FEATURE_COUNT = ModelPackage.ACTIVITY_NODE_FEATURE_COUNT + 7;

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.StartNode <em>Start Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Start Node</em>'.
	 * @see org.openiaml.model.model.operations.StartNode
	 * @generated
	 */
	EClass getStartNode();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.CancelNode <em>Cancel Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Cancel Node</em>'.
	 * @see org.openiaml.model.model.operations.CancelNode
	 * @generated
	 */
	EClass getCancelNode();

	/**
	 * Returns the meta object for the attribute '{@link org.openiaml.model.model.operations.CancelNode#getExceptionText <em>Exception Text</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Exception Text</em>'.
	 * @see org.openiaml.model.model.operations.CancelNode#getExceptionText()
	 * @see #getCancelNode()
	 * @generated
	 */
	EAttribute getCancelNode_ExceptionText();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.FinishNode <em>Finish Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Finish Node</em>'.
	 * @see org.openiaml.model.model.operations.FinishNode
	 * @generated
	 */
	EClass getFinishNode();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.DecisionNode <em>Decision Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Decision Node</em>'.
	 * @see org.openiaml.model.model.operations.DecisionNode
	 * @generated
	 */
	EClass getDecisionNode();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.DecisionOperation <em>Decision Operation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Decision Operation</em>'.
	 * @see org.openiaml.model.model.operations.DecisionOperation
	 * @generated
	 */
	EClass getDecisionOperation();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.DecisionCondition <em>Decision Condition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Decision Condition</em>'.
	 * @see org.openiaml.model.model.operations.DecisionCondition
	 * @generated
	 */
	EClass getDecisionCondition();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.SplitNode <em>Split Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Split Node</em>'.
	 * @see org.openiaml.model.model.operations.SplitNode
	 * @generated
	 */
	EClass getSplitNode();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.JoinNode <em>Join Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Join Node</em>'.
	 * @see org.openiaml.model.model.operations.JoinNode
	 * @generated
	 */
	EClass getJoinNode();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.operations.OperationCallNode <em>Operation Call Node</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Operation Call Node</em>'.
	 * @see org.openiaml.model.model.operations.OperationCallNode
	 * @generated
	 */
	EClass getOperationCallNode();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	OperationsFactory getOperationsFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.StartNodeImpl <em>Start Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.StartNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getStartNode()
		 * @generated
		 */
		EClass START_NODE = eINSTANCE.getStartNode();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.CancelNodeImpl <em>Cancel Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.CancelNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getCancelNode()
		 * @generated
		 */
		EClass CANCEL_NODE = eINSTANCE.getCancelNode();

		/**
		 * The meta object literal for the '<em><b>Exception Text</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CANCEL_NODE__EXCEPTION_TEXT = eINSTANCE.getCancelNode_ExceptionText();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.FinishNodeImpl <em>Finish Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.FinishNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getFinishNode()
		 * @generated
		 */
		EClass FINISH_NODE = eINSTANCE.getFinishNode();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.DecisionNodeImpl <em>Decision Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.DecisionNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionNode()
		 * @generated
		 */
		EClass DECISION_NODE = eINSTANCE.getDecisionNode();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.DecisionOperationImpl <em>Decision Operation</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.DecisionOperationImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionOperation()
		 * @generated
		 */
		EClass DECISION_OPERATION = eINSTANCE.getDecisionOperation();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.DecisionConditionImpl <em>Decision Condition</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.DecisionConditionImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getDecisionCondition()
		 * @generated
		 */
		EClass DECISION_CONDITION = eINSTANCE.getDecisionCondition();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.SplitNodeImpl <em>Split Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.SplitNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getSplitNode()
		 * @generated
		 */
		EClass SPLIT_NODE = eINSTANCE.getSplitNode();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.JoinNodeImpl <em>Join Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.JoinNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getJoinNode()
		 * @generated
		 */
		EClass JOIN_NODE = eINSTANCE.getJoinNode();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.operations.impl.OperationCallNodeImpl <em>Operation Call Node</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.operations.impl.OperationCallNodeImpl
		 * @see org.openiaml.model.model.operations.impl.OperationsPackageImpl#getOperationCallNode()
		 * @generated
		 */
		EClass OPERATION_CALL_NODE = eINSTANCE.getOperationCallNode();

	}

} //OperationsPackage
