/**
 * 
 */
package org.openiaml.verification.nusmv.tests;


/**
 * Tests all IAML models with the NuSMV verification.
 * TODO Contains all of the models in IAML as of r1414. 
 * 
 * @author jmwright
 *
 */
public class TestAllIAMLModels extends AbstractNuSMVTestCase {
	
	/*
	 * Automatically generated.
	 */
	
	public void test1() throws Exception { assertValid("../../demos/calculator/calculator.iaml", 0); }
	public void test2() throws Exception { assertValid("../../org.openiaml.emf.properties.tests/tests/BigInfiniteLoop-2.iaml", 0); }
	//public void test3() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/infer-output/InputFormInstanceMapping.iaml", 0); }
	//public void test4() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/infer-output/NewInstanceWireMapping.iaml", 0); }
	//public void test5() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/infer-output/PropertiesFileMapping.iaml", 0); }
	public void test6() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/DerivedPropertyMarker.iaml", 0); }
	public void test7() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/DeleteGeneratedElements.iaml", 0); }
	public void test8() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/FormDomainObjectMapping.iaml", 0); }
	public void test9() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/GenerateCodeActionTest.iaml", 0); }
	public void test10() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/NonContainedEdges.iaml", 0); }
	public void test11() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/PartialInference.iaml", 0); }
	public void test12() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/actions/RemovePhantomEdges.iaml", 0); }
	public void test13() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/generation-sync-multiple.iaml", 0); }
	// public void test14() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/migration/JoinSplitClientSide-0_4.iaml", 0); }
	// public void test15() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/migration/codegen-sync-pages-0_2.iaml", 0); }
	// public void test16() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/migration/model0_3/FileDomainObjects.iaml", 0); }
	// public void test17() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/migration/signup-form-0_1.iaml", 0); }
	public void test18() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts-root.iaml", 0); }
	public void test19() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/Issue69.iaml", 0); }
	public void test20() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/SeparatedInstances.iaml", 0); }
	public void test21() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/issue47.iaml", 0); }
	public void test22() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-domain_object.iaml", 0); }
	public void test23() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-domain_store.iaml", 0); }
	public void test24() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-element.iaml", 0); }
	public void test25() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-many.iaml", 0); }
	public void test26() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-operation.iaml", 0); }
	public void test27() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-root.iaml", 0); }
	public void test28() throws Exception { assertValid("../../org.openiaml.model.tests.diagram/src/org/openiaml/model/tests/eclipse/shortcuts/shortcuts-wire.iaml", 0); }
	public void test29() throws Exception { assertValid("../../org.openiaml.model.tests.elements/CompositeOperation.iaml", 0); }
	public void test30() throws Exception { assertValid("../../org.openiaml.model.tests.elements/DomainStore.iaml", 0); }
	public void test31() throws Exception { assertValid("../../org.openiaml.model.tests.elements/DynamicApplicationElementSet.iaml", 0); }
	public void test32() throws Exception { assertValid("../../org.openiaml.model.tests.elements/EventTrigger.iaml", 0); }
	public void test33() throws Exception { assertValid("../../org.openiaml.model.tests.elements/LoginHandler.iaml", 0); }
	public void test34() throws Exception { assertValid("../../org.openiaml.model.tests.elements/Page.iaml", 0); }
	public void test35() throws Exception { assertValid("../../org.openiaml.model.tests.elements/PrimitiveOperation.iaml", 0); }
	public void test36() throws Exception { assertValid("../../org.openiaml.model.tests.elements/Session.iaml", 0); }
	public void test37() throws Exception { assertValid("../../org.openiaml.model.tests.elements/Session2.iaml", 0); }
	public void test38() throws Exception { assertValid("../../org.openiaml.model.tests.elements/SyncWire.iaml", 0); }
	public void test39() throws Exception { assertValid("../../org.openiaml.model.tests.elements/UserStore.iaml", 0); }
	//public void test40() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/AddOperation.iaml", 0); }
	public void test41() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ArithmeticAdd.iaml", 0); }
	public void test42() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ArithmeticAddServer.iaml", 0); }
	public void test43() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ArithmeticDivide.iaml", 0); }
	public void test44() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ArithmeticMultiply.iaml", 0); }
	public void test45() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ArithmeticSubtract.iaml", 0); }
	public void test46() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ButtonNavigate.iaml", 0); }
	public void test47() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ButtonSetValue.iaml", 0); }
	public void test48() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ChecksTest.iaml", 0); }
	public void test49() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ComparisonFunctions.iaml", 0); }
	public void test50() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ConditionWireFalse.iaml", 0); }
	public void test51() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ConditionWireFalseServer.iaml", 0); }
	public void test52() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ConditionWireXpath.iaml", 0); }
	public void test53() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ConditionWireXpathThreePages.iaml", 0); }
	public void test54() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/DataFlowTemporaryVariable.iaml", 0); }
	public void test55() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/DatabaseWithInputForm.iaml", 0); }
	public void test56() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/DomainInheritance.iaml", 0); }
	public void test57() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/DomainInheritanceEditing.iaml", 0); }
	public void test58() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/DomainInstanceSaveOperation.iaml", 0); }
	public void test59() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/FailingOperation.iaml", 0); }
	public void test60() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/FailingOperationHandler.iaml", 0); }
	public void test61() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/FailingOperationHandlerSession.iaml", 0); }
	public void test62() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/FailingOperationHandlerSessionContained.iaml", 0); }
	public void test63() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/FailingOperationHandlerSessionMultiple.iaml", 0); }
	public void test64() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/GeneratedPrimaryKey.iaml", 0); }
	public void test65() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/HelperFunctions.iaml", 0); }
	public void test66() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/InputFormInstanceMapping.iaml", 0); }
	public void test67() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/JavascriptMethodsTest.iaml", 0); }
	public void test68() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/JoinSplitClientSide.iaml", 0); }
	public void test69() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/JoinSplitServerSide.iaml", 0); }
	public void test70() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoadModelTestCase.iaml", 0); }
	public void test71() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoginHandlerInstance.iaml", 0); }
	public void test72() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoginHandlerInstanceComplete.iaml", 0); }
	public void test73() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoginHandlerInstanceMultiple.iaml", 0); }
	public void test74() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoginHandlerKey.iaml", 0); }
	public void test75() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/LoginHandlerUser.iaml", 0); }
	public void test76() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceAttributeSession.iaml", 0); }
	public void test77() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceAttributeSessionAutosave.iaml", 0); }
	public void test78() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceObject.iaml", 0); }
	public void test79() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceObjectAutosave.iaml", 0); }
	public void test80() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceWireMapping.iaml", 0); }
	public void test81() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/NewInstanceWithoutId.iaml", 0); }
	public void test82() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/OperationCallNode.iaml", 0); }
	public void test83() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/PhpMethodsTest.iaml", 0); }
	public void test84() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/PropertiesFileMapping.iaml", 0); }
	public void test85() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/PropertiesFileWithInputForm.iaml", 0); }
	public void test86() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/QueryParameterAsParameter.iaml", 0); }
	public void test87() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/QueryParameterSet.iaml", 0); }
	public void test88() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/ReloadPage.iaml", 0); }
	public void test89() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement1SyncWires.iaml", 0); }
	public void test90() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement2StaticParams.iaml", 0); }
	public void test91() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement3DynamicParams.iaml", 0); }
	public void test92() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement4DynamicSources.iaml", 0); }
	public void test93() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement5Operations.iaml", 0); }
	public void test94() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/Requirement6Conditions.iaml", 0); }
	public void test95() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SavedRuleSources.iaml", 0); }
	public void test96() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectField.iaml", 0); }
	public void test97() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldExplicit.iaml", 0); }
	public void test98() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldFromDynamicObject.iaml", 0); }
	public void test99() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldFromDynamicQuery.iaml", 0); }
	public void test100() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldFromDynamicQueryAutosave.iaml", 0); }
	public void test101() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldFromObject.iaml", 0); }
	public void test102() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldFromObjectQuery.iaml", 0); }
	public void test103() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectFieldQuery.iaml", 0); }
	public void test104() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectMissing.iaml", 0); }
	public void test105() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectMissingExpected.iaml", 0); }
	public void test106() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SelectWireAttributeInference.iaml", 0); }
	public void test107() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SeparatedInstances.iaml", 0); }
	public void test108() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionInit.iaml", 0); }
	public void test109() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionNewDomainInstance.iaml", 0); }
	public void test110() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionSinglePage.iaml", 0); }
	public void test111() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionSyncInSession.iaml", 0); }
	public void test112() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionSyncWires.iaml", 0); }
	public void test113() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SessionSyncWiresMultiple.iaml", 0); }
	public void test114() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetValueStatic.iaml", 0); }
	public void test115() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetWireChained.iaml", 0); }
	public void test116() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetWireClient.iaml", 0); }
	public void test117() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetWireRemote.iaml", 0); }
	public void test118() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetWireSync.iaml", 0); }
	public void test119() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SetWireSyncChained.iaml", 0); }
	public void test120() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SimpleTestCase.iaml", 0); }
	public void test121() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/StoreCookie.iaml", 0); }
	public void test122() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncFieldApplicationElementProperty.iaml", 0); }
	public void test123() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncFieldDomainAttribute.iaml", 0); }
	public void test124() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncFormDomainObject.iaml", 0); }
	public void test125() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncStaticValueField.iaml", 0); }
	public void test126() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWireProperties.iaml", 0); }
	public void test127() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWireTestCase.iaml", 0); }
	public void test128() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWiresMultiple.iaml", 0); }
	public void test129() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWiresPagesTestCase.iaml", 0); }
	public void test130() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWiresProperties.iaml", 0); }
	public void test131() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/SyncWiresTestCase.iaml", 0); }
	public void test132() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/TestExceptionHandling.iaml", 0); }
	public void test133() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/TestIncludeLibraries.iaml", 0); }
	public void test134() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/TestProgressMonitor.iaml", 0); }
	public void test135() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserCreateRoles.iaml", 0); }
	public void test136() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserModifyRoles.iaml", 0); }
	public void test137() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserMultiplePermissions.iaml", 0); }
	public void test138() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserMultiplePermissionsAndRoles.iaml", 0); }
	public void test139() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserMultiplePermissionsOr.iaml", 0); }
	public void test140() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserMultiplePermissionsOrRoles.iaml", 0); }
	public void test141() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserPermissions.iaml", 0); }
	public void test142() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserPermissionsPage.iaml", 0); }
	public void test143() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserPermissionsRecursive.iaml", 0); }
	public void test144() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserRoleExtends.iaml", 0); }
	public void test145() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserRoles.iaml", 0); }
	public void test146() throws Exception { assertValid("../../org.openiaml.model.tests/infer-output/UserRolesLoginHandler.iaml", 0); }
	public void test147() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/codegen/codegen-simple.iaml", 0); }
	public void test148() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/codegen/codegen-sync-pages.iaml", 0); }
	public void test149() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/codegen/generation-sync.iaml", 0); }
	public void test150() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/icwe2009/sync_wires.iaml", 0); }
	public void test151() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/icwe2009/sync_wires_full.iaml", 0); }
	public void test152() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/inference/sync-wires.complete.iaml", 0); }
	public void test153() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/inference/sync-wires.iaml", 0); }
	public void test154() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/presentations/seat-plugin-example.iaml", 0); }
	public void test155() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/presentations/wires.iaml", 0); }
	public void test156() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/1-sync_wires.iaml", 0); }
	public void test157() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/2-static_params.iaml", 0); }
	public void test158() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/3-dynamic_params.iaml", 0); }
	public void test159() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/4-dynamic_sources.iaml", 0); }
	public void test160() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/5-operations.iaml", 0); }
	public void test161() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/6-conditions.iaml", 0); }
	public void test162() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/operations/JavascriptAlert.iaml", 0); }
	public void test163() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/operations/Set.iaml", 0); }
	public void test164() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/requirements/operations/SetPropertyToValue.iaml", 0); }
	public void test165() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/generation-delete.iaml", 0); }
	public void test166() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/generation-override.iaml", 0); }
	public void test167() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/generation-sync-form-domain.iaml", 0); }
	public void test168() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/generation-sync-multiple.iaml", 0); }
	public void test169() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/generation-sync.iaml", 0); }
	public void test170() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-domain_object.iaml", 0); }
	public void test171() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-domain_store.iaml", 0); }
	public void test172() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-element.iaml", 0); }
	public void test173() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-many.iaml", 0); }
	public void test174() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-operation.iaml", 0); }
	public void test175() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-root.iaml", 0); }
	public void test176() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/shortcuts-wire.iaml", 0); }
	public void test177() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/examples/tests/sync-fields.iaml", 0); }
	public void test178() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/blank.iaml", 0); }
	public void test179() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/ThrowException.iaml", 0); }
	public void test180() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/LoginHandlerKey.iaml", 0); }
	public void test181() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SimpleTestCase.iaml", 0); }
	public void test182() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncFieldApplicationElementProperty.iaml", 0); }
	public void test183() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncFieldDomainAttribute.iaml", 0); }
	public void test184() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncFormDomainObject.iaml", 0); }
	public void test185() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncStaticValueField.iaml", 0); }
	public void test186() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncWiresMultiple.iaml", 0); }
	public void test187() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncWiresPagesTestCase.iaml", 0); }
	public void test188() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncWiresProperties.iaml", 0); }
	public void test189() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_1/SyncWiresTestCase.iaml", 0); }
	public void test190() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_2/ConditionWireFalse.iaml", 0); }
	public void test191() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_2/ConditionWireFalseServer.iaml", 0); }
	public void test192() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_2/ReloadPage.iaml", 0); }
	public void test193() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/ButtonNavigate.iaml", 0); }
	public void test194() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/ButtonSetValue.iaml", 0); }
	public void test195() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/DataFlowTemporaryVariable.iaml", 0); }
	public void test196() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/DatabaseWithInputForm.iaml", 0); }
	public void test197() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/FailingOperation.iaml", 0); }
	public void test198() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/FailingOperationHandler.iaml", 0); }
	public void test199() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/FailingOperationHandlerSession.iaml", 0); }
	public void test200() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/FailingOperationHandlerSessionContained.iaml", 0); }
	public void test201() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/FailingOperationHandlerSessionMultiple.iaml", 0); }
	public void test202() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/NewInstanceAttributeSession.iaml", 0); }
	public void test203() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/NewInstanceAttributeSessionAutosave.iaml", 0); }
	public void test204() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/NewInstanceObject.iaml", 0); }
	public void test205() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/NewInstanceObjectAutosave.iaml", 0); }
	public void test206() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/PropertiesFileWithInputForm.iaml", 0); }
	public void test207() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectField.iaml", 0); }
	public void test208() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldExplicit.iaml", 0); }
	public void test209() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldFromDynamicObject.iaml", 0); }
	public void test210() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldFromDynamicQuery.iaml", 0); }
	public void test211() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldFromDynamicQueryAutosave.iaml", 0); }
	public void test212() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldFromObject.iaml", 0); }
	public void test213() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldFromObjectQuery.iaml", 0); }
	public void test214() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectFieldQuery.iaml", 0); }
	public void test215() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectMissing.iaml", 0); }
	public void test216() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectMissingExpected.iaml", 0); }
	public void test217() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectSessionField.iaml", 0); }
	public void test218() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SelectSessionObject.iaml", 0); }
	public void test219() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SessionInit.iaml", 0); }
	public void test220() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SessionSinglePage.iaml", 0); }
	public void test221() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SessionSyncInSession.iaml", 0); }
	public void test222() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SessionSyncWires.iaml", 0); }
	public void test223() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/SessionSyncWiresMultiple.iaml", 0); }
	public void test224() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_3/TestProgressMonitor.iaml", 0); }
	public void test225() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/DomainInheritance.iaml", 0); }
	public void test226() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/DomainInheritanceEditing.iaml", 0); }
	public void test227() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/JoinSplitClientSide.iaml", 0); }
	public void test228() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/JoinSplitServerSide.iaml", 0); }
	public void test229() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/LoginHandlerInstance.iaml", 0); }
	public void test230() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/LoginHandlerInstanceComplete.iaml", 0); }
	public void test231() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/LoginHandlerInstanceMultiple.iaml", 0); }
	public void test232() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/LoginHandlerUser.iaml", 0); }
	public void test233() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/NewInstanceWithoutId.iaml", 0); }
	public void test234() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/OperationCallNode.iaml", 0); }
	public void test235() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/QueryParameterAsParameter.iaml", 0); }
	public void test236() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/QueryParameterSet.iaml", 0); }
	public void test237() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SessionNewDomainInstance.iaml", 0); }
	public void test238() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SetWireChained.iaml", 0); }
	public void test239() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SetWireClient.iaml", 0); }
	public void test240() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SetWireRemote.iaml", 0); }
	public void test241() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SetWireSync.iaml", 0); }
	public void test242() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/SetWireSyncChained.iaml", 0); }
	public void test243() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserCreateRoles.iaml", 0); }
	public void test244() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserModifyRoles.iaml", 0); }
	public void test245() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserMultiplePermissions.iaml", 0); }
	public void test246() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserMultiplePermissionsAndRoles.iaml", 0); }
	public void test247() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserMultiplePermissionsOr.iaml", 0); }
	public void test248() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserPermissions.iaml", 0); }
	public void test249() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserPermissionsPage.iaml", 0); }
	public void test250() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserPermissionsRecursive.iaml", 0); }
	public void test251() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserRoleExtends.iaml", 0); }
	public void test252() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserRoles.iaml", 0); }
	public void test253() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4/UserRolesLoginHandler.iaml", 0); }
	public void test254() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ArithmeticAdd.iaml", 0); }
	public void test255() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ArithmeticAddServer.iaml", 0); }
	public void test256() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ArithmeticDivide.iaml", 0); }
	public void test257() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ArithmeticMultiply.iaml", 0); }
	public void test258() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ArithmeticSubtract.iaml", 0); }
	public void test259() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/ExplicitLoop.iaml", 0); }
	public void test260() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/model0_4_1/SetValueStatic.iaml", 0); }
	public void test261() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/oaw/NoPages.iaml", 0); }
	public void test262() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/runtime/client/JavascriptCodegenTestCase.iaml", 0); }
	public void test263() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/codegen/runtime/server/PhpCodegenTestCase.iaml", 0); }
	public void test264() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/ConditionWireFalse.iaml", 0); }
	public void test265() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/ConditionWireFalseServer.iaml", 0); }
	public void test266() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/ConditionWireXpath.iaml", 0); }
	public void test267() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/ConditionWireXpathThreePages.iaml", 0); }
	public void test268() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/DatabaseWithInputForm.iaml", 0); }
	public void test269() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/LoadModelTestCase.iaml", 0); }
	public void test270() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/PropertiesFileWithInputForm.iaml", 0); }
	public void test271() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SelectField.iaml", 0); }
	public void test272() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SelectFieldFromObject.iaml", 0); }
	public void test273() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SessionSyncWires.iaml", 0); }
	public void test274() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SyncFieldDomainAttribute.iaml", 0); }
	public void test275() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SyncFormDomainObject.iaml", 0); }
	public void test276() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SyncWireProperties.iaml", 0); }
	public void test277() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/SyncWireTestCase.iaml", 0); }
	public void test278() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_3/InputFormInstanceMapping.iaml", 0); }
	public void test279() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_3/NewInstanceWireMapping.iaml", 0); }
	public void test280() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_3/PropertiesFileMapping.iaml", 0); }
	public void test281() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/DomainInheritance.iaml", 0); }
	public void test282() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/DomainInheritanceEditing.iaml", 0); }
	public void test283() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/DomainInstanceSaveOperation.iaml", 0); }
	public void test284() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/GeneratedPrimaryKey.iaml", 0); }
	public void test285() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/LoginHandlerInstance.iaml", 0); }
	public void test286() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/LoginHandlerInstanceMultiple.iaml", 0); }
	public void test287() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/LoginHandlerKey.iaml", 0); }
	public void test288() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/OperationCallNode.iaml", 0); }
	public void test289() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/SelectWireAttributeInference.iaml", 0); }
	public void test290() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/SessionNewDomainInstance.iaml", 0); }
	public void test291() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/SetWireClient.iaml", 0); }
	public void test292() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/UserModifyRoles.iaml", 0); }
	public void test293() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/UserRoles.iaml", 0); }
	public void test294() throws Exception { assertValid("../../org.openiaml.model.tests/src/org/openiaml/model/tests/inference/model0_4/UserRolesLoginHandler.iaml", 0); }
	//public void test295() throws Exception { assertValid("../../org.openiaml.verification.tests/infer-output/CreateBigModels.iaml", 0); }
	public void test296() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/ConnectedToHome.iaml", 0); }
	public void test297() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/InfiniteRedirect.iaml", 0); }
	public void test298() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/InfiniteRedirectBig.iaml", 0); }
	public void test299() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/InfiniteRedirectBigCompleted.iaml", 0); }
	public void test300() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/SecurePageInitial.iaml", 0); }
	public void test301() throws Exception { assertValid("../../org.openiaml.verification.tests/tests/SecurePageInitialCompleted.iaml", 0); }
	public void test302() throws Exception { assertValid("../../verification/org.openiaml.model.owl/tests/NewInstanceObject.iaml", 0); }
	public void test303() throws Exception { assertValid("../../verification/org.openiaml.model.owl/tests/NoPages.iaml", 0); }
	public void test304() throws Exception { assertValid("../../verification/org.openiaml.model.owl/tests/SimpleTestCase.iaml", 0); }
	public void test305() throws Exception { assertValid("../../verification/org.openiaml.model.owl/tests/SyncWiresPagesTestCase.iaml", 0); }
	public void test306() throws Exception { assertValid("../../verification/org.openiaml.model.owl/tests/UserRolesLoginHandler.iaml", 0); }
	public void test307() throws Exception { assertValid("../../verification/org.openiaml.verification.crocopat.tests/src/org/openiaml/verification/crocopat/tests/BigInfiniteLoop-10.iaml", 0); }
	public void test308() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/AccessOperationLoop.iaml", 0); }
	public void test309() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/AccessOperationLoopInfinite.iaml", 0); }
	public void test310() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/DecisionOperationLoop.iaml", 0); }
	public void test311() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/DecisionOperationLoopInfinite.iaml", 0); }
	public void test312() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/InfiniteOperationLoop.iaml", 0); }
	public void test313() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/NormalOperationLoop.iaml", 0); }
	public void test314() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/OperationCallOperationLoop.iaml", 0); }
	public void test315() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/OperationCallOperationLoopInfinite.iaml", 0); }
	public void test316() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/SplitOperation.iaml", 0); }
	public void test317() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/SplitOperationDecision.iaml", 0); }
	public void test318() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/SplitOperationDecisionInfinite.iaml", 0); }
	public void test319() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/models/SplitOperationInfinite.iaml", 0); }
	public void test320() throws Exception { assertValid("../../verification/org.openiaml.verification.nusmv.tests/tests/BigInfiniteLoop-10.iaml", 0); }
		
}
