<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplegmf"
    nsURI="http://openiaml.org/simplegmf" nsPrefix="sgmf">
  <eClassifiers xsi:type="ecore:EClass" name="GMFConfiguration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figureConfigurations" upperBound="-1"
        eType="#//FigureConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeConfigurations" upperBound="-1"
        eType="#//EdgeConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customShapes" upperBound="-1"
        eType="#//CustomShape" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelConfigurations" upperBound="-1"
        eType="#//LabelConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPaletteTitle" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconBundle" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="palettes" upperBound="-1"
        eType="#//PaletteGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramEditors" upperBound="-1"
        eType="#//DiagramEditor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeTypes" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeReferences" upperBound="-1"
        eType="#//EdgeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFigure" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//FigureProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureConfiguration" eSuperTypes="#//AbstractFigure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//BuiltinShapes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customShape" eType="#//CustomShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinShapes">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="RECTANGLE" value="1"/>
    <eLiterals name="ELLIPSE" value="2" literal="ELLIPSE"/>
    <eLiterals name="ROUNDED_RECTANGLE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinPatterns">
    <eLiterals name="SOLID"/>
    <eLiterals name="DASH" value="1"/>
    <eLiterals name="DOT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeConfiguration" eSuperTypes="#//AbstractFigure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceArrow" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetArrow" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomShape" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelConfiguration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultText" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentFeature" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//LabelProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialLabel" eType="#//BuiltinLabels"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewPattern" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editPattern" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorPattern" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedAtRuntime" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinLabels">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="CONTAINMENT_NAME" value="1"/>
    <eLiterals name="METACLASS_NAME" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaletteGroup" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramEditor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//DiagramElement" containment="true" eOpposite="#//DiagramElement/editor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentFeatures" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" eType="#//DiagramEditor"
        eOpposite="#//DiagramEditor/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainedNode" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedNode" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainedEdge" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedEdge" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FigureProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabelProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinePattern" eSuperTypes="#//FigureProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linePattern" eType="#//BuiltinPatterns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowLayout" eSuperTypes="#//FigureProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowLayout" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="majorAlignment" eType="#//BuiltinAlignments"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minorAlignment" eType="#//BuiltinAlignments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineWidth" eSuperTypes="#//FigureProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureMargin" eSuperTypes="#//FigureProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="margin" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BackgroundColor" eSuperTypes="#//FigureProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForegroundColor" eSuperTypes="#//FigureProperty #//LabelProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelBold" eSuperTypes="#//LabelProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelUnderline" eSuperTypes="#//LabelProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinAlignments">
    <eLiterals name="BEGINNING"/>
    <eLiterals name="CENTER" value="1"/>
    <eLiterals name="END" value="2"/>
    <eLiterals name="FILL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeReference" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFeature" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFeature" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
</ecore:EPackage>
