<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://openiaml.org/model" nsPrefix="iaml">
  <eClassifiers xsi:type="ecore:EClass" name="NamdElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isGenerated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedElements" upperBound="-1"
        eType="#//NamdElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//WireEdgesSource"
        eOpposite="#//WireEdgesSource/outEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//WireEdgeDestination"
        eOpposite="#//WireEdgeDestination/inEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgeDestination" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEdges" upperBound="-1"
        eType="#//WireEdge" eOpposite="#//WireEdge/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WireEdgesSource" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEdges" upperBound="-1"
        eType="#//WireEdge" eOpposite="#//WireEdge/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElement" eSuperTypes="#//NamdElement #//WireEdgesSource #//WireEdgeDestination">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElementContainer" abstract="true"
      eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisibleThing" eSuperTypes="#//ApplicationElementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternetApplication" eSuperTypes="#//NamdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ApplicationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainStores" upperBound="-1"
        containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="not sure if this is necessary anymore... because now objects are stored as part of their scopes"/>
        <details key="changed" value="0.2 to extend the abstract counterpart"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://localhost:8080/output/"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginHandlers" upperBound="-1"
        containment="true">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="visual" nsURI="http://openiaml.org/model/visual" nsPrefix="iaml.visual">
    <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="Scope supertype added in 0.2"/>
        <details key="comment2" value="represents the scope Window"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputForm" eSuperTypes="#//VisibleThing"/>
    <eClassifiers xsi:type="ecore:EClass" name="InputTextField" eSuperTypes="#//VisibleThing"/>
    <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Frame" eSuperTypes="#//VisibleThing">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="added" value="0.2"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="wires" nsURI="http://openiaml.org/model/wires" nsPrefix="iaml.wires">
    <eClassifiers xsi:type="ecore:EClass" name="SingleWire" eSuperTypes="#//WireEdge">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="why do we have SingleWire at all? (following a design pattern?)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeWire" eSuperTypes="#//WireEdge #//NamdElement">
      <eAnnotations source="http://openiaml.org/comment">
        <details key="comment" value="ideally this would be abstract; but we want to have a &quot;wire&quot; diagram editor, and the root element needs to be concrete. the other option is to have multiple diagram editors per concrete wire..."/>
        <details key="comment2" value="easy visualisation: all composite wires are dashed"/>
        <details key="comment3" value="only composite wires have a name now"/>
        <details key="editor" value="org.openiaml.model.diagram.wire"/>
        <details key="comment4" value="a wire shouldn't have parameters; but the operations contained within need them rendered."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//ApplicationElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventTriggers" upperBound="-1"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SyncWire" eSuperTypes="#//wires/CompositeWire"/>
  </eSubpackages>
</ecore:EPackage>
