package org.openiaml.model.drools

#list any import classes here.
import org.eclipse.emf.ecore.*;
import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.scopes.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global EcoreCreateElementsHelper handler;

# insertion queue
import org.openiaml.model.drools.*;
global DroolsInsertionQueue queue;

rule "Create a TextField within a Page"
	when
		a : Page ( )
		not ( tf : InputTextField ( eContainer == a, name == "created" ))
		
	then
		InputTextField tf = handler.generatedInputTextField( a, a );
		handler.setName(tf, "created");
		queue.add(tf, drools);
end

rule "Create elements outside the contained element"
	when
		ia : InternetApplication ( )
		a : Page ( eContainer == ia, name == "target" )
		not ( f : InputForm ( eContainer == a, name == "created" ))
		not ( p : Page ( eContainer == ia, name == "outside activation" ))
		
	then
		InputForm f = handler.generatedInputForm( a, a );
		handler.setName(f, "created");
		queue.add(f, drools);
		
		Page p = handler.generatedPage(ia, ia);
		handler.setName(p, "outside activation");
		queue.add(p, drools);
end
