/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openiaml.model.model.domain;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EPackage;

import org.openiaml.model.model.ModelPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.openiaml.model.model.domain.DomainFactory
 * @model kind="package"
 * @generated
 */
public interface DomainPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "domain";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://openiaml.org/model/domain";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "iaml.domain";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	DomainPackage eINSTANCE = org.openiaml.model.model.domain.impl.DomainPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.domain.impl.FileDomainStoreImpl <em>File Domain Store</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.domain.impl.FileDomainStoreImpl
	 * @see org.openiaml.model.model.domain.impl.DomainPackageImpl#getFileDomainStore()
	 * @generated
	 */
	int FILE_DOMAIN_STORE = 0;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__GENERATED_BY = ModelPackage.NAMED_ELEMENT__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__IS_GENERATED = ModelPackage.NAMED_ELEMENT__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__ID = ModelPackage.NAMED_ELEMENT__ID;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__NAME = ModelPackage.NAMED_ELEMENT__NAME;

	/**
	 * The feature id for the '<em><b>Temp Type String</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__TEMP_TYPE_STRING = ModelPackage.NAMED_ELEMENT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE__FILE = ModelPackage.NAMED_ELEMENT_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>File Domain Store</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FILE_DOMAIN_STORE_FEATURE_COUNT = ModelPackage.NAMED_ELEMENT_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '<em>File Reference</em>' data type.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.FileReference
	 * @see org.openiaml.model.model.domain.impl.DomainPackageImpl#getFileReference()
	 * @generated
	 */
	int FILE_REFERENCE = 1;


	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.domain.FileDomainStore <em>File Domain Store</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>File Domain Store</em>'.
	 * @see org.openiaml.model.model.domain.FileDomainStore
	 * @generated
	 */
	EClass getFileDomainStore();

	/**
	 * Returns the meta object for the attribute '{@link org.openiaml.model.model.domain.FileDomainStore#getTempTypeString <em>Temp Type String</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Temp Type String</em>'.
	 * @see org.openiaml.model.model.domain.FileDomainStore#getTempTypeString()
	 * @see #getFileDomainStore()
	 * @generated
	 */
	EAttribute getFileDomainStore_TempTypeString();

	/**
	 * Returns the meta object for the attribute '{@link org.openiaml.model.model.domain.FileDomainStore#getFile <em>File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>File</em>'.
	 * @see org.openiaml.model.model.domain.FileDomainStore#getFile()
	 * @see #getFileDomainStore()
	 * @generated
	 */
	EAttribute getFileDomainStore_File();

	/**
	 * Returns the meta object for data type '{@link org.openiaml.model.FileReference <em>File Reference</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for data type '<em>File Reference</em>'.
	 * @see org.openiaml.model.FileReference
	 * @model instanceClass="org.openiaml.model.FileReference"
	 * @generated
	 */
	EDataType getFileReference();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	DomainFactory getDomainFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.domain.impl.FileDomainStoreImpl <em>File Domain Store</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.domain.impl.FileDomainStoreImpl
		 * @see org.openiaml.model.model.domain.impl.DomainPackageImpl#getFileDomainStore()
		 * @generated
		 */
		EClass FILE_DOMAIN_STORE = eINSTANCE.getFileDomainStore();

		/**
		 * The meta object literal for the '<em><b>Temp Type String</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FILE_DOMAIN_STORE__TEMP_TYPE_STRING = eINSTANCE.getFileDomainStore_TempTypeString();

		/**
		 * The meta object literal for the '<em><b>File</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FILE_DOMAIN_STORE__FILE = eINSTANCE.getFileDomainStore_File();

		/**
		 * The meta object literal for the '<em>File Reference</em>' data type.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.FileReference
		 * @see org.openiaml.model.model.domain.impl.DomainPackageImpl#getFileReference()
		 * @generated
		 */
		EDataType FILE_REFERENCE = eINSTANCE.getFileReference();

	}

} //DomainPackage
