package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate a
 * @version Tue Oct 28 12:15:47 NZDT 2008
 */
public class a {
    public org.openiaml.model.model.InternetApplication slot1;

    public a(org.openiaml.model.model.InternetApplication slot1) {
        super();
        this.slot1 = slot1;
    }

    public a() {
        super();
    }

    public String toString() {
        return "a[slot1=" + slot1 + "]";
    }

    //test4
}
