package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store factsInternetApplication_Children
 * for the predicate app_children
 * @version Tue Oct 28 12:15:47 NZDT 2008
 */
public interface ExternalFactStore4app_children {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<iaml.generated2.app_children> fetch(
        org.openiaml.model.model.InternetApplication slot1,
        org.openiaml.model.model.ApplicationElement slot2);
}
