package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store facts2
 * for the predicate app_children
 * @version Tue Oct 14 11:48:58 NZDT 2008
 */
public interface ExternalFactStore4InternetApplication_Children {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<iaml.generated2.InternetApplication_Children> fetch(
        org.openiaml.model.diagram.custom.takeproxy.InternetApplicationProxy slot1,
        org.openiaml.model.diagram.custom.takeproxy.ApplicationElementProxy slot2);
}
