package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store factsInputForm_Name
 * for the predicate input_form_name
 * @version Tue Oct 14 21:29:18 NZDT 2008
 */
public interface ExternalFactStore4input_form_name {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<iaml.generated2.input_form_name> fetch(
        org.openiaml.model.model.visual.InputForm slot1, java.lang.String slot2);
}
