package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store facts3
 * for the predicate element_children
 * @version Tue Oct 14 18:47:45 NZDT 2008
 */
public interface ExternalFactStore4ApplicationElementContainer_Children {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<iaml.generated2.ApplicationElementContainer_Children> fetch(
        org.openiaml.model.model.ApplicationElementContainer slot1,
        org.openiaml.model.model.ApplicationElement slot2);
}
