package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate app_children
 * @version Tue Oct 14 11:48:58 NZDT 2008
 */
public class InternetApplication_Children {
    public org.openiaml.model.diagram.custom.takeproxy.InternetApplicationProxy slot1;
    public org.openiaml.model.diagram.custom.takeproxy.ApplicationElementProxy slot2;

    public InternetApplication_Children(
        org.openiaml.model.diagram.custom.takeproxy.InternetApplicationProxy slot1,
        org.openiaml.model.diagram.custom.takeproxy.ApplicationElementProxy slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public InternetApplication_Children() {
        super();
    }
}
