package iaml.generated2;

/**
 * Class generated by the take compiler.
 * This class represents the predicate app_name
 * @version Tue Oct 14 21:20:36 NZDT 2008
 */
public class InternetApplication_Name {
    public org.openiaml.model.model.InternetApplication app;
    public java.lang.String string;

    public InternetApplication_Name(
        org.openiaml.model.model.InternetApplication app,
        java.lang.String string) {
        super();
        this.app = app;
        this.string = string;
    }

    public InternetApplication_Name() {
        super();
    }

    public String toString() {
        return "InternetApplication_Name[app=" + app + ", string=" + string +
        "]";
    }

    //test4
}
