package iaml.generated2;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Tue Oct 14 23:16:03 NZDT 2008
 */
@SuppressWarnings("unchecked")
class KBFragement_page_name_11 {
    /**
     * Method generated for query /page_name[in,in]
     * @param slot1 input parameter generated from slot 0
     * @param slot2 input parameter generated from slot 1
     * @return an iterator for instances of page_name
    */
    public static ResultSet<page_name> page_name_11(
        final org.openiaml.model.model.visual.Page slot1,
        final java.lang.String slot2) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<page_name> _result = new ResultSet(KBFragement_page_name_11.page_name_11(
                    slot1, slot2, _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query /page_name[in,in]
     * @param slot1 input parameter generated from slot 0
     * @param slot2 input parameter generated from slot 1
     * @return an iterator for instances of page_name
    */
    static ResourceIterator<page_name> page_name_11(
        final org.openiaml.model.model.visual.Page slot1,
        final java.lang.String slot2, final DerivationController _derivation) {
        final int _derivationlevel = _derivation.getDepth();
        ResourceIterator<page_name> result = new IteratorChain<page_name>(1) {
                public Object getIteratorOrObject(int pos) {
                    switch (pos) {
                    // factsPage_Name nz.org.take.ExternalFactStore@7a1576
                    case 0:
                        return page_name_11_0(slot1, slot2,
                            _derivation.reset(_derivationlevel));

                    default:
                        return EmptyIterator.DEFAULT;
                    } // switch(pos)
                } // getIterator()

                public String getRuleRef(int pos) {
                    switch (pos) {
                    // factsPage_Name nz.org.take.ExternalFactStore@7a1576
                    case 0:
                        return "factsPage_Name";

                    default:
                        return "";
                    } // switch(pos)
                } // getRuleRef()
            };

        return result;
    }

    /**
     * Method generated for query /page_name[in,in]
     * @param slot1 input parameter generated from slot 0
     * @param slot2 input parameter generated from slot 1
     * @return an iterator for instances of page_name
    */
    private static ResourceIterator<page_name> page_name_11_0(
        final org.openiaml.model.model.visual.Page slot1,
        final java.lang.String slot2, final DerivationController _derivation) {
        _derivation.log("factsPage_Name",
            DerivationController.EXTERNAL_FACT_SET, slot1, slot2);

        return FactStores.factsPage_Name.fetch(slot1, slot2);
    }
}
