package org.openiaml.model.drools.rules.conditions

#list any import classes here.
import org.openiaml.model.drools.*;

import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global OverridableCreateElementsHelper handler;
global DroolsInsertionQueue queue;
global DroolsHelperFunctions functions;

# TODO can we put this function into something global?
function boolean connects(Wire wire, Object a, Object b) {
	return (wire.getFrom().equals(a) && wire.getTo().equals(b)) ||
		(wire.getFrom().equals(b) && wire.getTo().equals(a));
}

# @inference SyncWire,RunAction,ConditionEdge {@model RunAction RunActions} with incoming {@model ConditionEdge conditions} will be copied to elements created by {@model SyncWire SyncWires}.
rule "Connect ConditionEdges to RunActions created by SyncWires (edit/update) (onChange)"
	when
		# we have a sync wire
		sw : SyncWire( )
		source : Changeable( )
		target : ContainsOperations( )
		eval(functions.connects(sw, source, target))  
		
		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )		
		run : RunAction( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

rule "Connect ConditionEdges to RunActions created by SyncWires (access/init) (onAccess)"
	when
		# we have a sync wire
		sw : SyncWire( )
		source : Accessible( )
		target : ContainsOperations( )
		eval(functions.connects(sw, source, target))  
		
		# which has a run wire between event and operation (generated)
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )		
		run : RunAction( eContainer == sw, from == event, to == operation, name == "run" )
		
		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue )
		param : ParameterEdge ( from == fvalue, to == run ) 
		
		# and the sync wire had a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# but our run wire doesn't 
		not (ConditionEdge (from == condition, to == run )) 
			
		eval ( handler.veto( sourceCw ))
		
	then
		# copy the condition
		ConditionEdge cw = handler.generatedConditionEdge( sourceCw, sw, condition, run );
		handler.setName(cw, "copied condition: " + sourceCw.getId());
		queue.add(cw, drools);

end

/**
 * @inference SyncWire,RunAction,ConditionEdge,ParameterEdge 
 *		{@model RunAction RunActions} with incoming {@model ConditionEdge conditions} 
 *		with {@model ParameterEdge parameters} will be copied to elements 
 *		created by {@model SyncWire SyncWires}.
 */
rule "Connect ParameterEdges to ConditionEdges connected to RunActions created by SyncWires (edit/update) (onChange)"
	when
		# we have a syncwire
		sw : SyncWire( )
		source : Changeable( )
		target : ContainsOperations( )
		eval(functions.connects(sw, source, target))  
		
		# that has created a RunAction
		event : EventTrigger( source.onChange == event )
		operation : Operation( eContainer == target, name=="update" )
		run : RunAction( eContainer == sw, from == event, to == operation, name == "run" )

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the RunAction has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end

rule "Connect ParameterEdges to ConditionEdges connected to RunActions created by SyncWires (access/init) (onAccess)"
	when
		# we have a syncwire
		sw : SyncWire( )
		source : Accessible( )
		target : ContainsOperations( )
		eval(functions.connects(sw, source, target))  
		
		# that has created a RunAction
		event : EventTrigger( source.onAccess == event )
		operation : Operation( eContainer == source, name=="init" )
		run : RunAction( eContainer == sw, from == event, to == operation, name == "run" )

		# and targets' value is being used for source's init
		fvalue : Property ( target.fieldValue == fvalue ) 
		param2 : ParameterEdge ( from == fvalue, to == run ) 

		# and this SyncWire has a condition
		condition : Condition ( )
		sourceCw : ConditionEdge( from == condition, to == sw )
		
		# and the RunAction has the same condition 
		targetCw : ConditionEdge (from == condition, to == run ) 
		
		# and the SyncWire had a parameter
		param : ParameterEdgesSource ( )
		paramWire : ParameterEdge( from == param, to == sourceCw )

		# but this wire does not have it
		not (ParameterEdge (from == param, to == targetCw ))
			
		eval ( handler.veto( sourceCw ))
		
	then
		ParameterEdge pw = handler.generatedParameterEdge( sourceCw, sw, param, targetCw );
		//cw.setName("copied parameter: " + paramWire.getName());
		handler.setName(pw, "[conditions] sync from: " + paramWire.getId() + " param=" + ((GeneratedElement) param).getId() + " run=" + run.getId() );
		queue.add(pw, drools);

end
