package org.openiaml.model.drools

#list any import classes here.
import org.openiaml.model.drools.*;

import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.scopes.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global EcoreCreateElementsHelper handler;
global DroolsInsertionQueue queue;
global DroolsHelperFunctions functions;

rule "Create a TextField within a Frame"
	when
		a : Frame ( )
		not ( tf : InputTextField ( eContainer == a, name == "created" ))
		
	then
		InputTextField tf = handler.generatedInputTextField( a, a );
		handler.setName(tf, "created");
		queue.add(tf, drools);
end

rule "Create elements outside the contained element"
	when
		ia : InternetApplication ( )
		a : Frame ( eContainer == ia, name == "target" )
		not ( f : InputForm ( eContainer == a, name == "created" ))
		not ( p : Frame ( eContainer == ia, name == "outside activation" ))
		
	then
		InputForm f = handler.generatedInputForm( a, a );
		handler.setName(f, "created");
		queue.add(f, drools);
		
		Frame p = handler.generatedFrame(ia, ia);
		handler.setName(p, "outside activation");
		queue.add(p, drools);
end
