#created on: 4/11/2008
package org.openiaml.model.drools.rules.sessions

#list any import classes here.
import org.openiaml.model.drools.*;

import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.scopes.*;
import org.openiaml.model.model.components.*;

#declare any global variables here
global EcoreCreateElementsHelper handler;
global DroolsInsertionQueue queue;
global DroolsHelperFunctions functions;

rule "Create 'access' event for all pages"
	when
		page : Page( )
		not (EventTrigger (eContainer == page, name=="access" ))
					
	then
		EventTrigger access = handler.generatedEventTrigger(page, page);
		handler.setName(access, "access");
		queue.add(access, drools);
		
end

rule "Create 'init' event for Sessions"
	when
		session : Session( overridden == false )
		not (EventTrigger( eContainer == session, name == "init" ))
		
	then
		EventTrigger event = handler.generatedEventTrigger(session, session);
		handler.setName(event, "init");
		queue.add(event, drools);
	
end

rule "Create 'access' event for Sessions"
	when
		session : Session( overridden == false )
		not (EventTrigger( eContainer == session, name == "access" ))
		
	then
		EventTrigger event = handler.generatedEventTrigger(session, session);
		handler.setName(event, "access");
		queue.add(event, drools);
	
end

