/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openiaml.model.model.components;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

import org.openiaml.model.model.ModelPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.openiaml.model.model.components.ComponentsFactory
 * @model kind="package"
 *        annotation="http://openiaml.org/comment added='0.2'"
 * @generated
 */
public interface ComponentsPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "components";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://openiaml.org/model/components";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "iaml.components";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	ComponentsPackage eINSTANCE = org.openiaml.model.model.components.impl.ComponentsPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.components.impl.LoginHandlerImpl <em>Login Handler</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.components.impl.LoginHandlerImpl
	 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandler()
	 * @generated
	 */
	int LOGIN_HANDLER = 0;

	/**
	 * The feature id for the '<em><b>Operations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__OPERATIONS = ModelPackage.APPLICATION_ELEMENT_CONTAINER__OPERATIONS;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__GENERATED_BY = ModelPackage.APPLICATION_ELEMENT_CONTAINER__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__IS_GENERATED = ModelPackage.APPLICATION_ELEMENT_CONTAINER__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__ID = ModelPackage.APPLICATION_ELEMENT_CONTAINER__ID;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__NAME = ModelPackage.APPLICATION_ELEMENT_CONTAINER__NAME;

	/**
	 * The feature id for the '<em><b>Event Triggers</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__EVENT_TRIGGERS = ModelPackage.APPLICATION_ELEMENT_CONTAINER__EVENT_TRIGGERS;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__WIRES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__WIRES;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__OUT_EDGES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__OUT_EDGES;

	/**
	 * The feature id for the '<em><b>In Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__IN_EDGES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__IN_EDGES;

	/**
	 * The feature id for the '<em><b>Generated Elements</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__GENERATED_ELEMENTS = ModelPackage.APPLICATION_ELEMENT_CONTAINER__GENERATED_ELEMENTS;

	/**
	 * The feature id for the '<em><b>Overridden</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__OVERRIDDEN = ModelPackage.APPLICATION_ELEMENT_CONTAINER__OVERRIDDEN;

	/**
	 * The feature id for the '<em><b>Domain Objects</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__DOMAIN_OBJECTS = ModelPackage.APPLICATION_ELEMENT_CONTAINER__DOMAIN_OBJECTS;

	/**
	 * The feature id for the '<em><b>Domain Views</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__DOMAIN_VIEWS = ModelPackage.APPLICATION_ELEMENT_CONTAINER__DOMAIN_VIEWS;

	/**
	 * The feature id for the '<em><b>Domain Instances</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__DOMAIN_INSTANCES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__DOMAIN_INSTANCES;

	/**
	 * The feature id for the '<em><b>Properties</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__PROPERTIES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__PROPERTIES;

	/**
	 * The feature id for the '<em><b>Values</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__VALUES = ModelPackage.APPLICATION_ELEMENT_CONTAINER__VALUES;

	/**
	 * The feature id for the '<em><b>Children</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER__CHILDREN = ModelPackage.APPLICATION_ELEMENT_CONTAINER__CHILDREN;

	/**
	 * The number of structural features of the '<em>Login Handler</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_FEATURE_COUNT = ModelPackage.APPLICATION_ELEMENT_CONTAINER_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.components.impl.LoginHandlerKeyImpl <em>Login Handler Key</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.components.impl.LoginHandlerKeyImpl
	 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandlerKey()
	 * @generated
	 */
	int LOGIN_HANDLER_KEY = 1;

	/**
	 * The feature id for the '<em><b>Operations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__OPERATIONS = LOGIN_HANDLER__OPERATIONS;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__GENERATED_BY = LOGIN_HANDLER__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__IS_GENERATED = LOGIN_HANDLER__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__ID = LOGIN_HANDLER__ID;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__NAME = LOGIN_HANDLER__NAME;

	/**
	 * The feature id for the '<em><b>Event Triggers</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__EVENT_TRIGGERS = LOGIN_HANDLER__EVENT_TRIGGERS;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__WIRES = LOGIN_HANDLER__WIRES;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__OUT_EDGES = LOGIN_HANDLER__OUT_EDGES;

	/**
	 * The feature id for the '<em><b>In Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__IN_EDGES = LOGIN_HANDLER__IN_EDGES;

	/**
	 * The feature id for the '<em><b>Generated Elements</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__GENERATED_ELEMENTS = LOGIN_HANDLER__GENERATED_ELEMENTS;

	/**
	 * The feature id for the '<em><b>Overridden</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__OVERRIDDEN = LOGIN_HANDLER__OVERRIDDEN;

	/**
	 * The feature id for the '<em><b>Domain Objects</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__DOMAIN_OBJECTS = LOGIN_HANDLER__DOMAIN_OBJECTS;

	/**
	 * The feature id for the '<em><b>Domain Views</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__DOMAIN_VIEWS = LOGIN_HANDLER__DOMAIN_VIEWS;

	/**
	 * The feature id for the '<em><b>Domain Instances</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__DOMAIN_INSTANCES = LOGIN_HANDLER__DOMAIN_INSTANCES;

	/**
	 * The feature id for the '<em><b>Properties</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__PROPERTIES = LOGIN_HANDLER__PROPERTIES;

	/**
	 * The feature id for the '<em><b>Values</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__VALUES = LOGIN_HANDLER__VALUES;

	/**
	 * The feature id for the '<em><b>Children</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__CHILDREN = LOGIN_HANDLER__CHILDREN;

	/**
	 * The feature id for the '<em><b>Secret Key</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY__SECRET_KEY = LOGIN_HANDLER_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Login Handler Key</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_KEY_FEATURE_COUNT = LOGIN_HANDLER_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.openiaml.model.model.components.impl.LoginHandlerDomainObjectImpl <em>Login Handler Domain Object</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.openiaml.model.model.components.impl.LoginHandlerDomainObjectImpl
	 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandlerDomainObject()
	 * @generated
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT = 2;

	/**
	 * The feature id for the '<em><b>Operations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__OPERATIONS = LOGIN_HANDLER__OPERATIONS;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__GENERATED_BY = LOGIN_HANDLER__GENERATED_BY;

	/**
	 * The feature id for the '<em><b>Is Generated</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__IS_GENERATED = LOGIN_HANDLER__IS_GENERATED;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__ID = LOGIN_HANDLER__ID;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__NAME = LOGIN_HANDLER__NAME;

	/**
	 * The feature id for the '<em><b>Event Triggers</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__EVENT_TRIGGERS = LOGIN_HANDLER__EVENT_TRIGGERS;

	/**
	 * The feature id for the '<em><b>Wires</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__WIRES = LOGIN_HANDLER__WIRES;

	/**
	 * The feature id for the '<em><b>Out Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__OUT_EDGES = LOGIN_HANDLER__OUT_EDGES;

	/**
	 * The feature id for the '<em><b>In Edges</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__IN_EDGES = LOGIN_HANDLER__IN_EDGES;

	/**
	 * The feature id for the '<em><b>Generated Elements</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__GENERATED_ELEMENTS = LOGIN_HANDLER__GENERATED_ELEMENTS;

	/**
	 * The feature id for the '<em><b>Overridden</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__OVERRIDDEN = LOGIN_HANDLER__OVERRIDDEN;

	/**
	 * The feature id for the '<em><b>Domain Objects</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__DOMAIN_OBJECTS = LOGIN_HANDLER__DOMAIN_OBJECTS;

	/**
	 * The feature id for the '<em><b>Domain Views</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__DOMAIN_VIEWS = LOGIN_HANDLER__DOMAIN_VIEWS;

	/**
	 * The feature id for the '<em><b>Domain Instances</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__DOMAIN_INSTANCES = LOGIN_HANDLER__DOMAIN_INSTANCES;

	/**
	 * The feature id for the '<em><b>Properties</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__PROPERTIES = LOGIN_HANDLER__PROPERTIES;

	/**
	 * The feature id for the '<em><b>Values</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__VALUES = LOGIN_HANDLER__VALUES;

	/**
	 * The feature id for the '<em><b>Children</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT__CHILDREN = LOGIN_HANDLER__CHILDREN;

	/**
	 * The number of structural features of the '<em>Login Handler Domain Object</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LOGIN_HANDLER_DOMAIN_OBJECT_FEATURE_COUNT = LOGIN_HANDLER_FEATURE_COUNT + 0;


	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.components.LoginHandler <em>Login Handler</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Login Handler</em>'.
	 * @see org.openiaml.model.model.components.LoginHandler
	 * @generated
	 */
	EClass getLoginHandler();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.components.LoginHandlerKey <em>Login Handler Key</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Login Handler Key</em>'.
	 * @see org.openiaml.model.model.components.LoginHandlerKey
	 * @generated
	 */
	EClass getLoginHandlerKey();

	/**
	 * Returns the meta object for the attribute '{@link org.openiaml.model.model.components.LoginHandlerKey#getSecretKey <em>Secret Key</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Secret Key</em>'.
	 * @see org.openiaml.model.model.components.LoginHandlerKey#getSecretKey()
	 * @see #getLoginHandlerKey()
	 * @generated
	 */
	EAttribute getLoginHandlerKey_SecretKey();

	/**
	 * Returns the meta object for class '{@link org.openiaml.model.model.components.LoginHandlerDomainObject <em>Login Handler Domain Object</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Login Handler Domain Object</em>'.
	 * @see org.openiaml.model.model.components.LoginHandlerDomainObject
	 * @generated
	 */
	EClass getLoginHandlerDomainObject();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	ComponentsFactory getComponentsFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.components.impl.LoginHandlerImpl <em>Login Handler</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.components.impl.LoginHandlerImpl
		 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandler()
		 * @generated
		 */
		EClass LOGIN_HANDLER = eINSTANCE.getLoginHandler();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.components.impl.LoginHandlerKeyImpl <em>Login Handler Key</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.components.impl.LoginHandlerKeyImpl
		 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandlerKey()
		 * @generated
		 */
		EClass LOGIN_HANDLER_KEY = eINSTANCE.getLoginHandlerKey();

		/**
		 * The meta object literal for the '<em><b>Secret Key</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute LOGIN_HANDLER_KEY__SECRET_KEY = eINSTANCE.getLoginHandlerKey_SecretKey();

		/**
		 * The meta object literal for the '{@link org.openiaml.model.model.components.impl.LoginHandlerDomainObjectImpl <em>Login Handler Domain Object</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.openiaml.model.model.components.impl.LoginHandlerDomainObjectImpl
		 * @see org.openiaml.model.model.components.impl.ComponentsPackageImpl#getLoginHandlerDomainObject()
		 * @generated
		 */
		EClass LOGIN_HANDLER_DOMAIN_OBJECT = eINSTANCE.getLoginHandlerDomainObject();

	}

} //ComponentsPackage
