/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openiaml.model.model.scopes.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.EObjectImpl;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.openiaml.model.model.Accessible;
import org.openiaml.model.model.Action;
import org.openiaml.model.model.ActionSource;
import org.openiaml.model.model.ApplicationElement;
import org.openiaml.model.model.CanBeSynced;
import org.openiaml.model.model.Condition;
import org.openiaml.model.model.ContainsConditions;
import org.openiaml.model.model.ContainsOperations;
import org.openiaml.model.model.ContainsProperties;
import org.openiaml.model.model.ContainsWires;
import org.openiaml.model.model.EventTrigger;
import org.openiaml.model.model.GeneratedElement;
import org.openiaml.model.model.GeneratesElements;
import org.openiaml.model.model.ModelPackage;
import org.openiaml.model.model.Operation;
import org.openiaml.model.model.Property;
import org.openiaml.model.model.QueryParameter;
import org.openiaml.model.model.Scope;
import org.openiaml.model.model.ShouldntContainWires;
import org.openiaml.model.model.StaticValue;
import org.openiaml.model.model.Wire;
import org.openiaml.model.model.WireDestination;
import org.openiaml.model.model.WireSource;
import org.openiaml.model.model.components.EntryGate;
import org.openiaml.model.model.components.ExitGate;
import org.openiaml.model.model.scopes.Email;
import org.openiaml.model.model.scopes.ScopesPackage;
import org.openiaml.model.model.visual.Button;
import org.openiaml.model.model.visual.Label;
import org.openiaml.model.model.wires.ConditionEdge;
import org.openiaml.model.model.wires.ConstraintEdge;
import org.openiaml.model.model.wires.ExtendsEdge;
import org.openiaml.model.model.wires.ParameterEdge;
import org.openiaml.model.model.wires.ProvidesEdge;
import org.openiaml.model.model.wires.RequiresEdge;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Email</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#isIsGenerated <em>Is Generated</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getGeneratedRule <em>Generated Rule</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOperations <em>Operations</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getGeneratedElements <em>Generated Elements</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#isOverridden <em>Overridden</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getWires <em>Wires</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getActions <em>Actions</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getParameterEdges <em>Parameter Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getExtendsEdges <em>Extends Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getRequiresEdges <em>Requires Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getProvidesEdges <em>Provides Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getConstraintEdges <em>Constraint Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getConditionEdges <em>Condition Edges</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOutWires <em>Out Wires</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getInWires <em>In Wires</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getConditions <em>Conditions</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOnAccess <em>On Access</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOutActions <em>Out Actions</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getEntryGate <em>Entry Gate</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getExitGate <em>Exit Gate</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getValues <em>Values</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getElements <em>Elements</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOnInit <em>On Init</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getScopes <em>Scopes</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getTo <em>To</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getToName <em>To Name</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getFromName <em>From Name</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOnSent <em>On Sent</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getOnFailure <em>On Failure</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getButtons <em>Buttons</em>}</li>
 *   <li>{@link org.openiaml.model.model.scopes.impl.EmailImpl#getLabels <em>Labels</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class EmailImpl extends EObjectImpl implements Email {
	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected EList<GeneratesElements> generatedBy;

	/**
	 * The default value of the '{@link #isIsGenerated() <em>Is Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isIsGenerated()
	 * @generated
	 * @ordered
	 */
	protected static final boolean IS_GENERATED_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isIsGenerated() <em>Is Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isIsGenerated()
	 * @generated
	 * @ordered
	 */
	protected boolean isGenerated = IS_GENERATED_EDEFAULT;

	/**
	 * The default value of the '{@link #getId() <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getId()
	 * @generated
	 * @ordered
	 */
	protected static final String ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getId()
	 * @generated
	 * @ordered
	 */
	protected String id = ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedRule() <em>Generated Rule</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedRule()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_RULE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedRule() <em>Generated Rule</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedRule()
	 * @generated
	 * @ordered
	 */
	protected String generatedRule = GENERATED_RULE_EDEFAULT;

	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The cached value of the '{@link #getOperations() <em>Operations</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOperations()
	 * @generated
	 * @ordered
	 */
	protected EList<Operation> operations;

	/**
	 * The cached value of the '{@link #getGeneratedElements() <em>Generated Elements</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedElements()
	 * @generated
	 * @ordered
	 */
	protected EList<GeneratedElement> generatedElements;

	/**
	 * The default value of the '{@link #isOverridden() <em>Overridden</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isOverridden()
	 * @generated
	 * @ordered
	 */
	protected static final boolean OVERRIDDEN_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isOverridden() <em>Overridden</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isOverridden()
	 * @generated
	 * @ordered
	 */
	protected boolean overridden = OVERRIDDEN_EDEFAULT;

	/**
	 * The cached value of the '{@link #getWires() <em>Wires</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getWires()
	 * @generated
	 * @ordered
	 */
	protected EList<Wire> wires;

	/**
	 * The cached value of the '{@link #getActions() <em>Actions</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getActions()
	 * @generated
	 * @ordered
	 */
	protected EList<Action> actions;

	/**
	 * The cached value of the '{@link #getParameterEdges() <em>Parameter Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getParameterEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<ParameterEdge> parameterEdges;

	/**
	 * The cached value of the '{@link #getExtendsEdges() <em>Extends Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getExtendsEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<ExtendsEdge> extendsEdges;

	/**
	 * The cached value of the '{@link #getRequiresEdges() <em>Requires Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRequiresEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<RequiresEdge> requiresEdges;

	/**
	 * The cached value of the '{@link #getProvidesEdges() <em>Provides Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getProvidesEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<ProvidesEdge> providesEdges;

	/**
	 * The cached value of the '{@link #getConstraintEdges() <em>Constraint Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getConstraintEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<ConstraintEdge> constraintEdges;

	/**
	 * The cached value of the '{@link #getConditionEdges() <em>Condition Edges</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getConditionEdges()
	 * @generated
	 * @ordered
	 */
	protected EList<ConditionEdge> conditionEdges;

	/**
	 * The cached value of the '{@link #getOutWires() <em>Out Wires</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOutWires()
	 * @generated
	 * @ordered
	 */
	protected EList<Wire> outWires;

	/**
	 * The cached value of the '{@link #getInWires() <em>In Wires</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getInWires()
	 * @generated
	 * @ordered
	 */
	protected EList<Wire> inWires;

	/**
	 * The cached value of the '{@link #getConditions() <em>Conditions</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getConditions()
	 * @generated
	 * @ordered
	 */
	protected EList<Condition> conditions;

	/**
	 * The cached value of the '{@link #getOnAccess() <em>On Access</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOnAccess()
	 * @generated
	 * @ordered
	 */
	protected EventTrigger onAccess;

	/**
	 * The cached value of the '{@link #getOutActions() <em>Out Actions</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOutActions()
	 * @generated
	 * @ordered
	 */
	protected EList<Action> outActions;

	/**
	 * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getProperties()
	 * @generated
	 * @ordered
	 */
	protected EList<Property> properties;

	/**
	 * The cached value of the '{@link #getEntryGate() <em>Entry Gate</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEntryGate()
	 * @generated
	 * @ordered
	 */
	protected EntryGate entryGate;

	/**
	 * The cached value of the '{@link #getExitGate() <em>Exit Gate</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getExitGate()
	 * @generated
	 * @ordered
	 */
	protected ExitGate exitGate;

	/**
	 * The cached value of the '{@link #getValues() <em>Values</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getValues()
	 * @generated
	 * @ordered
	 */
	protected EList<StaticValue> values;

	/**
	 * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getParameters()
	 * @generated
	 * @ordered
	 */
	protected EList<QueryParameter> parameters;

	/**
	 * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getElements()
	 * @generated
	 * @ordered
	 */
	protected EList<ApplicationElement> elements;

	/**
	 * The cached value of the '{@link #getOnInit() <em>On Init</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOnInit()
	 * @generated
	 * @ordered
	 */
	protected EventTrigger onInit;

	/**
	 * The cached value of the '{@link #getScopes() <em>Scopes</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getScopes()
	 * @generated
	 * @ordered
	 */
	protected EList<Scope> scopes;

	/**
	 * The default value of the '{@link #getTo() <em>To</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTo()
	 * @generated
	 * @ordered
	 */
	protected static final String TO_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getTo() <em>To</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTo()
	 * @generated
	 * @ordered
	 */
	protected String to = TO_EDEFAULT;

	/**
	 * The default value of the '{@link #getSubject() <em>Subject</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubject()
	 * @generated
	 * @ordered
	 */
	protected static final String SUBJECT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getSubject() <em>Subject</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubject()
	 * @generated
	 * @ordered
	 */
	protected String subject = SUBJECT_EDEFAULT;

	/**
	 * The default value of the '{@link #getToName() <em>To Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getToName()
	 * @generated
	 * @ordered
	 */
	protected static final String TO_NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getToName() <em>To Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getToName()
	 * @generated
	 * @ordered
	 */
	protected String toName = TO_NAME_EDEFAULT;

	/**
	 * The default value of the '{@link #getFrom() <em>From</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFrom()
	 * @generated
	 * @ordered
	 */
	protected static final String FROM_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getFrom() <em>From</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFrom()
	 * @generated
	 * @ordered
	 */
	protected String from = FROM_EDEFAULT;

	/**
	 * The default value of the '{@link #getFromName() <em>From Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFromName()
	 * @generated
	 * @ordered
	 */
	protected static final String FROM_NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getFromName() <em>From Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFromName()
	 * @generated
	 * @ordered
	 */
	protected String fromName = FROM_NAME_EDEFAULT;

	/**
	 * The cached value of the '{@link #getOnSent() <em>On Sent</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOnSent()
	 * @generated
	 * @ordered
	 */
	protected EventTrigger onSent;

	/**
	 * The cached value of the '{@link #getOnFailure() <em>On Failure</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOnFailure()
	 * @generated
	 * @ordered
	 */
	protected EventTrigger onFailure;

	/**
	 * The cached value of the '{@link #getButtons() <em>Buttons</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getButtons()
	 * @generated
	 * @ordered
	 */
	protected EList<Button> buttons;

	/**
	 * The cached value of the '{@link #getLabels() <em>Labels</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getLabels()
	 * @generated
	 * @ordered
	 */
	protected EList<Label> labels;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmailImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return ScopesPackage.Literals.EMAIL;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<GeneratesElements> getGeneratedBy() {
		if (generatedBy == null) {
			generatedBy = new EObjectWithInverseResolvingEList.ManyInverse<GeneratesElements>(GeneratesElements.class, this, ScopesPackage.EMAIL__GENERATED_BY, ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS);
		}
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isIsGenerated() {
		return isGenerated;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setIsGenerated(boolean newIsGenerated) {
		boolean oldIsGenerated = isGenerated;
		isGenerated = newIsGenerated;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__IS_GENERATED, oldIsGenerated, isGenerated));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setId(String newId) {
		String oldId = id;
		id = newId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ID, oldId, id));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getGeneratedRule() {
		return generatedRule;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGeneratedRule(String newGeneratedRule) {
		String oldGeneratedRule = generatedRule;
		generatedRule = newGeneratedRule;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__GENERATED_RULE, oldGeneratedRule, generatedRule));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Operation> getOperations() {
		if (operations == null) {
			operations = new EObjectContainmentEList<Operation>(Operation.class, this, ScopesPackage.EMAIL__OPERATIONS);
		}
		return operations;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<GeneratedElement> getGeneratedElements() {
		if (generatedElements == null) {
			generatedElements = new EObjectWithInverseResolvingEList.ManyInverse<GeneratedElement>(GeneratedElement.class, this, ScopesPackage.EMAIL__GENERATED_ELEMENTS, ModelPackage.GENERATED_ELEMENT__GENERATED_BY);
		}
		return generatedElements;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isOverridden() {
		return overridden;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOverridden(boolean newOverridden) {
		boolean oldOverridden = overridden;
		overridden = newOverridden;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__OVERRIDDEN, oldOverridden, overridden));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Wire> getWires() {
		if (wires == null) {
			wires = new EObjectContainmentEList<Wire>(Wire.class, this, ScopesPackage.EMAIL__WIRES);
		}
		return wires;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Action> getActions() {
		if (actions == null) {
			actions = new EObjectContainmentEList<Action>(Action.class, this, ScopesPackage.EMAIL__ACTIONS);
		}
		return actions;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ParameterEdge> getParameterEdges() {
		if (parameterEdges == null) {
			parameterEdges = new EObjectContainmentEList<ParameterEdge>(ParameterEdge.class, this, ScopesPackage.EMAIL__PARAMETER_EDGES);
		}
		return parameterEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ExtendsEdge> getExtendsEdges() {
		if (extendsEdges == null) {
			extendsEdges = new EObjectContainmentEList<ExtendsEdge>(ExtendsEdge.class, this, ScopesPackage.EMAIL__EXTENDS_EDGES);
		}
		return extendsEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<RequiresEdge> getRequiresEdges() {
		if (requiresEdges == null) {
			requiresEdges = new EObjectContainmentEList<RequiresEdge>(RequiresEdge.class, this, ScopesPackage.EMAIL__REQUIRES_EDGES);
		}
		return requiresEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ProvidesEdge> getProvidesEdges() {
		if (providesEdges == null) {
			providesEdges = new EObjectContainmentEList<ProvidesEdge>(ProvidesEdge.class, this, ScopesPackage.EMAIL__PROVIDES_EDGES);
		}
		return providesEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ConstraintEdge> getConstraintEdges() {
		if (constraintEdges == null) {
			constraintEdges = new EObjectContainmentEList<ConstraintEdge>(ConstraintEdge.class, this, ScopesPackage.EMAIL__CONSTRAINT_EDGES);
		}
		return constraintEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ConditionEdge> getConditionEdges() {
		if (conditionEdges == null) {
			conditionEdges = new EObjectContainmentEList<ConditionEdge>(ConditionEdge.class, this, ScopesPackage.EMAIL__CONDITION_EDGES);
		}
		return conditionEdges;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Wire> getOutWires() {
		if (outWires == null) {
			outWires = new EObjectWithInverseResolvingEList<Wire>(Wire.class, this, ScopesPackage.EMAIL__OUT_WIRES, ModelPackage.WIRE__FROM);
		}
		return outWires;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Wire> getInWires() {
		if (inWires == null) {
			inWires = new EObjectWithInverseResolvingEList<Wire>(Wire.class, this, ScopesPackage.EMAIL__IN_WIRES, ModelPackage.WIRE__TO);
		}
		return inWires;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Condition> getConditions() {
		if (conditions == null) {
			conditions = new EObjectContainmentEList<Condition>(Condition.class, this, ScopesPackage.EMAIL__CONDITIONS);
		}
		return conditions;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EventTrigger getOnAccess() {
		return onAccess;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetOnAccess(EventTrigger newOnAccess, NotificationChain msgs) {
		EventTrigger oldOnAccess = onAccess;
		onAccess = newOnAccess;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_ACCESS, oldOnAccess, newOnAccess);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOnAccess(EventTrigger newOnAccess) {
		if (newOnAccess != onAccess) {
			NotificationChain msgs = null;
			if (onAccess != null)
				msgs = ((InternalEObject)onAccess).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_ACCESS, null, msgs);
			if (newOnAccess != null)
				msgs = ((InternalEObject)newOnAccess).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_ACCESS, null, msgs);
			msgs = basicSetOnAccess(newOnAccess, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_ACCESS, newOnAccess, newOnAccess));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Action> getOutActions() {
		if (outActions == null) {
			outActions = new EObjectWithInverseResolvingEList<Action>(Action.class, this, ScopesPackage.EMAIL__OUT_ACTIONS, ModelPackage.ACTION__FROM);
		}
		return outActions;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Property> getProperties() {
		if (properties == null) {
			properties = new EObjectContainmentEList<Property>(Property.class, this, ScopesPackage.EMAIL__PROPERTIES);
		}
		return properties;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EntryGate getEntryGate() {
		return entryGate;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetEntryGate(EntryGate newEntryGate, NotificationChain msgs) {
		EntryGate oldEntryGate = entryGate;
		entryGate = newEntryGate;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ENTRY_GATE, oldEntryGate, newEntryGate);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setEntryGate(EntryGate newEntryGate) {
		if (newEntryGate != entryGate) {
			NotificationChain msgs = null;
			if (entryGate != null)
				msgs = ((InternalEObject)entryGate).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ENTRY_GATE, null, msgs);
			if (newEntryGate != null)
				msgs = ((InternalEObject)newEntryGate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ENTRY_GATE, null, msgs);
			msgs = basicSetEntryGate(newEntryGate, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ENTRY_GATE, newEntryGate, newEntryGate));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ExitGate getExitGate() {
		return exitGate;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetExitGate(ExitGate newExitGate, NotificationChain msgs) {
		ExitGate oldExitGate = exitGate;
		exitGate = newExitGate;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__EXIT_GATE, oldExitGate, newExitGate);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setExitGate(ExitGate newExitGate) {
		if (newExitGate != exitGate) {
			NotificationChain msgs = null;
			if (exitGate != null)
				msgs = ((InternalEObject)exitGate).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__EXIT_GATE, null, msgs);
			if (newExitGate != null)
				msgs = ((InternalEObject)newExitGate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__EXIT_GATE, null, msgs);
			msgs = basicSetExitGate(newExitGate, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__EXIT_GATE, newExitGate, newExitGate));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<StaticValue> getValues() {
		if (values == null) {
			values = new EObjectContainmentEList<StaticValue>(StaticValue.class, this, ScopesPackage.EMAIL__VALUES);
		}
		return values;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<QueryParameter> getParameters() {
		if (parameters == null) {
			parameters = new EObjectContainmentEList<QueryParameter>(QueryParameter.class, this, ScopesPackage.EMAIL__PARAMETERS);
		}
		return parameters;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<ApplicationElement> getElements() {
		if (elements == null) {
			elements = new EObjectContainmentEList<ApplicationElement>(ApplicationElement.class, this, ScopesPackage.EMAIL__ELEMENTS);
		}
		return elements;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EventTrigger getOnInit() {
		return onInit;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetOnInit(EventTrigger newOnInit, NotificationChain msgs) {
		EventTrigger oldOnInit = onInit;
		onInit = newOnInit;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_INIT, oldOnInit, newOnInit);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOnInit(EventTrigger newOnInit) {
		if (newOnInit != onInit) {
			NotificationChain msgs = null;
			if (onInit != null)
				msgs = ((InternalEObject)onInit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_INIT, null, msgs);
			if (newOnInit != null)
				msgs = ((InternalEObject)newOnInit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_INIT, null, msgs);
			msgs = basicSetOnInit(newOnInit, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_INIT, newOnInit, newOnInit));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Scope> getScopes() {
		if (scopes == null) {
			scopes = new EObjectContainmentEList<Scope>(Scope.class, this, ScopesPackage.EMAIL__SCOPES);
		}
		return scopes;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getTo() {
		return to;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTo(String newTo) {
		String oldTo = to;
		to = newTo;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__TO, oldTo, to));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setSubject(String newSubject) {
		String oldSubject = subject;
		subject = newSubject;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__SUBJECT, oldSubject, subject));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getToName() {
		return toName;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setToName(String newToName) {
		String oldToName = toName;
		toName = newToName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__TO_NAME, oldToName, toName));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getFrom() {
		return from;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setFrom(String newFrom) {
		String oldFrom = from;
		from = newFrom;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__FROM, oldFrom, from));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getFromName() {
		return fromName;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setFromName(String newFromName) {
		String oldFromName = fromName;
		fromName = newFromName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__FROM_NAME, oldFromName, fromName));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EventTrigger getOnSent() {
		return onSent;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetOnSent(EventTrigger newOnSent, NotificationChain msgs) {
		EventTrigger oldOnSent = onSent;
		onSent = newOnSent;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_SENT, oldOnSent, newOnSent);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOnSent(EventTrigger newOnSent) {
		if (newOnSent != onSent) {
			NotificationChain msgs = null;
			if (onSent != null)
				msgs = ((InternalEObject)onSent).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_SENT, null, msgs);
			if (newOnSent != null)
				msgs = ((InternalEObject)newOnSent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_SENT, null, msgs);
			msgs = basicSetOnSent(newOnSent, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_SENT, newOnSent, newOnSent));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EventTrigger getOnFailure() {
		return onFailure;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetOnFailure(EventTrigger newOnFailure, NotificationChain msgs) {
		EventTrigger oldOnFailure = onFailure;
		onFailure = newOnFailure;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_FAILURE, oldOnFailure, newOnFailure);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setOnFailure(EventTrigger newOnFailure) {
		if (newOnFailure != onFailure) {
			NotificationChain msgs = null;
			if (onFailure != null)
				msgs = ((InternalEObject)onFailure).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_FAILURE, null, msgs);
			if (newOnFailure != null)
				msgs = ((InternalEObject)newOnFailure).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ScopesPackage.EMAIL__ON_FAILURE, null, msgs);
			msgs = basicSetOnFailure(newOnFailure, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ScopesPackage.EMAIL__ON_FAILURE, newOnFailure, newOnFailure));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Button> getButtons() {
		if (buttons == null) {
			buttons = new EObjectContainmentEList<Button>(Button.class, this, ScopesPackage.EMAIL__BUTTONS);
		}
		return buttons;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Label> getLabels() {
		if (labels == null) {
			labels = new EObjectContainmentEList<Label>(Label.class, this, ScopesPackage.EMAIL__LABELS);
		}
		return labels;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getGeneratedBy()).basicAdd(otherEnd, msgs);
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getGeneratedElements()).basicAdd(otherEnd, msgs);
			case ScopesPackage.EMAIL__OUT_WIRES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getOutWires()).basicAdd(otherEnd, msgs);
			case ScopesPackage.EMAIL__IN_WIRES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getInWires()).basicAdd(otherEnd, msgs);
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getOutActions()).basicAdd(otherEnd, msgs);
		}
		return super.eInverseAdd(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				return ((InternalEList<?>)getGeneratedBy()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__OPERATIONS:
				return ((InternalEList<?>)getOperations()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				return ((InternalEList<?>)getGeneratedElements()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__WIRES:
				return ((InternalEList<?>)getWires()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ACTIONS:
				return ((InternalEList<?>)getActions()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__PARAMETER_EDGES:
				return ((InternalEList<?>)getParameterEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__EXTENDS_EDGES:
				return ((InternalEList<?>)getExtendsEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__REQUIRES_EDGES:
				return ((InternalEList<?>)getRequiresEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__PROVIDES_EDGES:
				return ((InternalEList<?>)getProvidesEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__CONSTRAINT_EDGES:
				return ((InternalEList<?>)getConstraintEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__CONDITION_EDGES:
				return ((InternalEList<?>)getConditionEdges()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__OUT_WIRES:
				return ((InternalEList<?>)getOutWires()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__IN_WIRES:
				return ((InternalEList<?>)getInWires()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__CONDITIONS:
				return ((InternalEList<?>)getConditions()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ON_ACCESS:
				return basicSetOnAccess(null, msgs);
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				return ((InternalEList<?>)getOutActions()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__PROPERTIES:
				return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ENTRY_GATE:
				return basicSetEntryGate(null, msgs);
			case ScopesPackage.EMAIL__EXIT_GATE:
				return basicSetExitGate(null, msgs);
			case ScopesPackage.EMAIL__VALUES:
				return ((InternalEList<?>)getValues()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__PARAMETERS:
				return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ELEMENTS:
				return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ON_INIT:
				return basicSetOnInit(null, msgs);
			case ScopesPackage.EMAIL__SCOPES:
				return ((InternalEList<?>)getScopes()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__ON_SENT:
				return basicSetOnSent(null, msgs);
			case ScopesPackage.EMAIL__ON_FAILURE:
				return basicSetOnFailure(null, msgs);
			case ScopesPackage.EMAIL__BUTTONS:
				return ((InternalEList<?>)getButtons()).basicRemove(otherEnd, msgs);
			case ScopesPackage.EMAIL__LABELS:
				return ((InternalEList<?>)getLabels()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				return getGeneratedBy();
			case ScopesPackage.EMAIL__IS_GENERATED:
				return isIsGenerated();
			case ScopesPackage.EMAIL__ID:
				return getId();
			case ScopesPackage.EMAIL__GENERATED_RULE:
				return getGeneratedRule();
			case ScopesPackage.EMAIL__NAME:
				return getName();
			case ScopesPackage.EMAIL__OPERATIONS:
				return getOperations();
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				return getGeneratedElements();
			case ScopesPackage.EMAIL__OVERRIDDEN:
				return isOverridden();
			case ScopesPackage.EMAIL__WIRES:
				return getWires();
			case ScopesPackage.EMAIL__ACTIONS:
				return getActions();
			case ScopesPackage.EMAIL__PARAMETER_EDGES:
				return getParameterEdges();
			case ScopesPackage.EMAIL__EXTENDS_EDGES:
				return getExtendsEdges();
			case ScopesPackage.EMAIL__REQUIRES_EDGES:
				return getRequiresEdges();
			case ScopesPackage.EMAIL__PROVIDES_EDGES:
				return getProvidesEdges();
			case ScopesPackage.EMAIL__CONSTRAINT_EDGES:
				return getConstraintEdges();
			case ScopesPackage.EMAIL__CONDITION_EDGES:
				return getConditionEdges();
			case ScopesPackage.EMAIL__OUT_WIRES:
				return getOutWires();
			case ScopesPackage.EMAIL__IN_WIRES:
				return getInWires();
			case ScopesPackage.EMAIL__CONDITIONS:
				return getConditions();
			case ScopesPackage.EMAIL__ON_ACCESS:
				return getOnAccess();
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				return getOutActions();
			case ScopesPackage.EMAIL__PROPERTIES:
				return getProperties();
			case ScopesPackage.EMAIL__ENTRY_GATE:
				return getEntryGate();
			case ScopesPackage.EMAIL__EXIT_GATE:
				return getExitGate();
			case ScopesPackage.EMAIL__VALUES:
				return getValues();
			case ScopesPackage.EMAIL__PARAMETERS:
				return getParameters();
			case ScopesPackage.EMAIL__ELEMENTS:
				return getElements();
			case ScopesPackage.EMAIL__ON_INIT:
				return getOnInit();
			case ScopesPackage.EMAIL__SCOPES:
				return getScopes();
			case ScopesPackage.EMAIL__TO:
				return getTo();
			case ScopesPackage.EMAIL__SUBJECT:
				return getSubject();
			case ScopesPackage.EMAIL__TO_NAME:
				return getToName();
			case ScopesPackage.EMAIL__FROM:
				return getFrom();
			case ScopesPackage.EMAIL__FROM_NAME:
				return getFromName();
			case ScopesPackage.EMAIL__ON_SENT:
				return getOnSent();
			case ScopesPackage.EMAIL__ON_FAILURE:
				return getOnFailure();
			case ScopesPackage.EMAIL__BUTTONS:
				return getButtons();
			case ScopesPackage.EMAIL__LABELS:
				return getLabels();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				getGeneratedBy().clear();
				getGeneratedBy().addAll((Collection<? extends GeneratesElements>)newValue);
				return;
			case ScopesPackage.EMAIL__IS_GENERATED:
				setIsGenerated((Boolean)newValue);
				return;
			case ScopesPackage.EMAIL__ID:
				setId((String)newValue);
				return;
			case ScopesPackage.EMAIL__GENERATED_RULE:
				setGeneratedRule((String)newValue);
				return;
			case ScopesPackage.EMAIL__NAME:
				setName((String)newValue);
				return;
			case ScopesPackage.EMAIL__OPERATIONS:
				getOperations().clear();
				getOperations().addAll((Collection<? extends Operation>)newValue);
				return;
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				getGeneratedElements().clear();
				getGeneratedElements().addAll((Collection<? extends GeneratedElement>)newValue);
				return;
			case ScopesPackage.EMAIL__OVERRIDDEN:
				setOverridden((Boolean)newValue);
				return;
			case ScopesPackage.EMAIL__WIRES:
				getWires().clear();
				getWires().addAll((Collection<? extends Wire>)newValue);
				return;
			case ScopesPackage.EMAIL__ACTIONS:
				getActions().clear();
				getActions().addAll((Collection<? extends Action>)newValue);
				return;
			case ScopesPackage.EMAIL__PARAMETER_EDGES:
				getParameterEdges().clear();
				getParameterEdges().addAll((Collection<? extends ParameterEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__EXTENDS_EDGES:
				getExtendsEdges().clear();
				getExtendsEdges().addAll((Collection<? extends ExtendsEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__REQUIRES_EDGES:
				getRequiresEdges().clear();
				getRequiresEdges().addAll((Collection<? extends RequiresEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__PROVIDES_EDGES:
				getProvidesEdges().clear();
				getProvidesEdges().addAll((Collection<? extends ProvidesEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__CONSTRAINT_EDGES:
				getConstraintEdges().clear();
				getConstraintEdges().addAll((Collection<? extends ConstraintEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__CONDITION_EDGES:
				getConditionEdges().clear();
				getConditionEdges().addAll((Collection<? extends ConditionEdge>)newValue);
				return;
			case ScopesPackage.EMAIL__OUT_WIRES:
				getOutWires().clear();
				getOutWires().addAll((Collection<? extends Wire>)newValue);
				return;
			case ScopesPackage.EMAIL__IN_WIRES:
				getInWires().clear();
				getInWires().addAll((Collection<? extends Wire>)newValue);
				return;
			case ScopesPackage.EMAIL__CONDITIONS:
				getConditions().clear();
				getConditions().addAll((Collection<? extends Condition>)newValue);
				return;
			case ScopesPackage.EMAIL__ON_ACCESS:
				setOnAccess((EventTrigger)newValue);
				return;
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				getOutActions().clear();
				getOutActions().addAll((Collection<? extends Action>)newValue);
				return;
			case ScopesPackage.EMAIL__PROPERTIES:
				getProperties().clear();
				getProperties().addAll((Collection<? extends Property>)newValue);
				return;
			case ScopesPackage.EMAIL__ENTRY_GATE:
				setEntryGate((EntryGate)newValue);
				return;
			case ScopesPackage.EMAIL__EXIT_GATE:
				setExitGate((ExitGate)newValue);
				return;
			case ScopesPackage.EMAIL__VALUES:
				getValues().clear();
				getValues().addAll((Collection<? extends StaticValue>)newValue);
				return;
			case ScopesPackage.EMAIL__PARAMETERS:
				getParameters().clear();
				getParameters().addAll((Collection<? extends QueryParameter>)newValue);
				return;
			case ScopesPackage.EMAIL__ELEMENTS:
				getElements().clear();
				getElements().addAll((Collection<? extends ApplicationElement>)newValue);
				return;
			case ScopesPackage.EMAIL__ON_INIT:
				setOnInit((EventTrigger)newValue);
				return;
			case ScopesPackage.EMAIL__SCOPES:
				getScopes().clear();
				getScopes().addAll((Collection<? extends Scope>)newValue);
				return;
			case ScopesPackage.EMAIL__TO:
				setTo((String)newValue);
				return;
			case ScopesPackage.EMAIL__SUBJECT:
				setSubject((String)newValue);
				return;
			case ScopesPackage.EMAIL__TO_NAME:
				setToName((String)newValue);
				return;
			case ScopesPackage.EMAIL__FROM:
				setFrom((String)newValue);
				return;
			case ScopesPackage.EMAIL__FROM_NAME:
				setFromName((String)newValue);
				return;
			case ScopesPackage.EMAIL__ON_SENT:
				setOnSent((EventTrigger)newValue);
				return;
			case ScopesPackage.EMAIL__ON_FAILURE:
				setOnFailure((EventTrigger)newValue);
				return;
			case ScopesPackage.EMAIL__BUTTONS:
				getButtons().clear();
				getButtons().addAll((Collection<? extends Button>)newValue);
				return;
			case ScopesPackage.EMAIL__LABELS:
				getLabels().clear();
				getLabels().addAll((Collection<? extends Label>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				getGeneratedBy().clear();
				return;
			case ScopesPackage.EMAIL__IS_GENERATED:
				setIsGenerated(IS_GENERATED_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__ID:
				setId(ID_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__GENERATED_RULE:
				setGeneratedRule(GENERATED_RULE_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__NAME:
				setName(NAME_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__OPERATIONS:
				getOperations().clear();
				return;
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				getGeneratedElements().clear();
				return;
			case ScopesPackage.EMAIL__OVERRIDDEN:
				setOverridden(OVERRIDDEN_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__WIRES:
				getWires().clear();
				return;
			case ScopesPackage.EMAIL__ACTIONS:
				getActions().clear();
				return;
			case ScopesPackage.EMAIL__PARAMETER_EDGES:
				getParameterEdges().clear();
				return;
			case ScopesPackage.EMAIL__EXTENDS_EDGES:
				getExtendsEdges().clear();
				return;
			case ScopesPackage.EMAIL__REQUIRES_EDGES:
				getRequiresEdges().clear();
				return;
			case ScopesPackage.EMAIL__PROVIDES_EDGES:
				getProvidesEdges().clear();
				return;
			case ScopesPackage.EMAIL__CONSTRAINT_EDGES:
				getConstraintEdges().clear();
				return;
			case ScopesPackage.EMAIL__CONDITION_EDGES:
				getConditionEdges().clear();
				return;
			case ScopesPackage.EMAIL__OUT_WIRES:
				getOutWires().clear();
				return;
			case ScopesPackage.EMAIL__IN_WIRES:
				getInWires().clear();
				return;
			case ScopesPackage.EMAIL__CONDITIONS:
				getConditions().clear();
				return;
			case ScopesPackage.EMAIL__ON_ACCESS:
				setOnAccess((EventTrigger)null);
				return;
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				getOutActions().clear();
				return;
			case ScopesPackage.EMAIL__PROPERTIES:
				getProperties().clear();
				return;
			case ScopesPackage.EMAIL__ENTRY_GATE:
				setEntryGate((EntryGate)null);
				return;
			case ScopesPackage.EMAIL__EXIT_GATE:
				setExitGate((ExitGate)null);
				return;
			case ScopesPackage.EMAIL__VALUES:
				getValues().clear();
				return;
			case ScopesPackage.EMAIL__PARAMETERS:
				getParameters().clear();
				return;
			case ScopesPackage.EMAIL__ELEMENTS:
				getElements().clear();
				return;
			case ScopesPackage.EMAIL__ON_INIT:
				setOnInit((EventTrigger)null);
				return;
			case ScopesPackage.EMAIL__SCOPES:
				getScopes().clear();
				return;
			case ScopesPackage.EMAIL__TO:
				setTo(TO_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__SUBJECT:
				setSubject(SUBJECT_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__TO_NAME:
				setToName(TO_NAME_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__FROM:
				setFrom(FROM_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__FROM_NAME:
				setFromName(FROM_NAME_EDEFAULT);
				return;
			case ScopesPackage.EMAIL__ON_SENT:
				setOnSent((EventTrigger)null);
				return;
			case ScopesPackage.EMAIL__ON_FAILURE:
				setOnFailure((EventTrigger)null);
				return;
			case ScopesPackage.EMAIL__BUTTONS:
				getButtons().clear();
				return;
			case ScopesPackage.EMAIL__LABELS:
				getLabels().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case ScopesPackage.EMAIL__GENERATED_BY:
				return generatedBy != null && !generatedBy.isEmpty();
			case ScopesPackage.EMAIL__IS_GENERATED:
				return isGenerated != IS_GENERATED_EDEFAULT;
			case ScopesPackage.EMAIL__ID:
				return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
			case ScopesPackage.EMAIL__GENERATED_RULE:
				return GENERATED_RULE_EDEFAULT == null ? generatedRule != null : !GENERATED_RULE_EDEFAULT.equals(generatedRule);
			case ScopesPackage.EMAIL__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case ScopesPackage.EMAIL__OPERATIONS:
				return operations != null && !operations.isEmpty();
			case ScopesPackage.EMAIL__GENERATED_ELEMENTS:
				return generatedElements != null && !generatedElements.isEmpty();
			case ScopesPackage.EMAIL__OVERRIDDEN:
				return overridden != OVERRIDDEN_EDEFAULT;
			case ScopesPackage.EMAIL__WIRES:
				return wires != null && !wires.isEmpty();
			case ScopesPackage.EMAIL__ACTIONS:
				return actions != null && !actions.isEmpty();
			case ScopesPackage.EMAIL__PARAMETER_EDGES:
				return parameterEdges != null && !parameterEdges.isEmpty();
			case ScopesPackage.EMAIL__EXTENDS_EDGES:
				return extendsEdges != null && !extendsEdges.isEmpty();
			case ScopesPackage.EMAIL__REQUIRES_EDGES:
				return requiresEdges != null && !requiresEdges.isEmpty();
			case ScopesPackage.EMAIL__PROVIDES_EDGES:
				return providesEdges != null && !providesEdges.isEmpty();
			case ScopesPackage.EMAIL__CONSTRAINT_EDGES:
				return constraintEdges != null && !constraintEdges.isEmpty();
			case ScopesPackage.EMAIL__CONDITION_EDGES:
				return conditionEdges != null && !conditionEdges.isEmpty();
			case ScopesPackage.EMAIL__OUT_WIRES:
				return outWires != null && !outWires.isEmpty();
			case ScopesPackage.EMAIL__IN_WIRES:
				return inWires != null && !inWires.isEmpty();
			case ScopesPackage.EMAIL__CONDITIONS:
				return conditions != null && !conditions.isEmpty();
			case ScopesPackage.EMAIL__ON_ACCESS:
				return onAccess != null;
			case ScopesPackage.EMAIL__OUT_ACTIONS:
				return outActions != null && !outActions.isEmpty();
			case ScopesPackage.EMAIL__PROPERTIES:
				return properties != null && !properties.isEmpty();
			case ScopesPackage.EMAIL__ENTRY_GATE:
				return entryGate != null;
			case ScopesPackage.EMAIL__EXIT_GATE:
				return exitGate != null;
			case ScopesPackage.EMAIL__VALUES:
				return values != null && !values.isEmpty();
			case ScopesPackage.EMAIL__PARAMETERS:
				return parameters != null && !parameters.isEmpty();
			case ScopesPackage.EMAIL__ELEMENTS:
				return elements != null && !elements.isEmpty();
			case ScopesPackage.EMAIL__ON_INIT:
				return onInit != null;
			case ScopesPackage.EMAIL__SCOPES:
				return scopes != null && !scopes.isEmpty();
			case ScopesPackage.EMAIL__TO:
				return TO_EDEFAULT == null ? to != null : !TO_EDEFAULT.equals(to);
			case ScopesPackage.EMAIL__SUBJECT:
				return SUBJECT_EDEFAULT == null ? subject != null : !SUBJECT_EDEFAULT.equals(subject);
			case ScopesPackage.EMAIL__TO_NAME:
				return TO_NAME_EDEFAULT == null ? toName != null : !TO_NAME_EDEFAULT.equals(toName);
			case ScopesPackage.EMAIL__FROM:
				return FROM_EDEFAULT == null ? from != null : !FROM_EDEFAULT.equals(from);
			case ScopesPackage.EMAIL__FROM_NAME:
				return FROM_NAME_EDEFAULT == null ? fromName != null : !FROM_NAME_EDEFAULT.equals(fromName);
			case ScopesPackage.EMAIL__ON_SENT:
				return onSent != null;
			case ScopesPackage.EMAIL__ON_FAILURE:
				return onFailure != null;
			case ScopesPackage.EMAIL__BUTTONS:
				return buttons != null && !buttons.isEmpty();
			case ScopesPackage.EMAIL__LABELS:
				return labels != null && !labels.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass) {
		if (baseClass == ContainsOperations.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__OPERATIONS: return ModelPackage.CONTAINS_OPERATIONS__OPERATIONS;
				default: return -1;
			}
		}
		if (baseClass == GeneratesElements.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__GENERATED_ELEMENTS: return ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS;
				case ScopesPackage.EMAIL__OVERRIDDEN: return ModelPackage.GENERATES_ELEMENTS__OVERRIDDEN;
				default: return -1;
			}
		}
		if (baseClass == ContainsWires.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__WIRES: return ModelPackage.CONTAINS_WIRES__WIRES;
				case ScopesPackage.EMAIL__ACTIONS: return ModelPackage.CONTAINS_WIRES__ACTIONS;
				case ScopesPackage.EMAIL__PARAMETER_EDGES: return ModelPackage.CONTAINS_WIRES__PARAMETER_EDGES;
				case ScopesPackage.EMAIL__EXTENDS_EDGES: return ModelPackage.CONTAINS_WIRES__EXTENDS_EDGES;
				case ScopesPackage.EMAIL__REQUIRES_EDGES: return ModelPackage.CONTAINS_WIRES__REQUIRES_EDGES;
				case ScopesPackage.EMAIL__PROVIDES_EDGES: return ModelPackage.CONTAINS_WIRES__PROVIDES_EDGES;
				case ScopesPackage.EMAIL__CONSTRAINT_EDGES: return ModelPackage.CONTAINS_WIRES__CONSTRAINT_EDGES;
				case ScopesPackage.EMAIL__CONDITION_EDGES: return ModelPackage.CONTAINS_WIRES__CONDITION_EDGES;
				default: return -1;
			}
		}
		if (baseClass == ShouldntContainWires.class) {
			switch (derivedFeatureID) {
				default: return -1;
			}
		}
		if (baseClass == WireSource.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__OUT_WIRES: return ModelPackage.WIRE_SOURCE__OUT_WIRES;
				default: return -1;
			}
		}
		if (baseClass == WireDestination.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__IN_WIRES: return ModelPackage.WIRE_DESTINATION__IN_WIRES;
				default: return -1;
			}
		}
		if (baseClass == ContainsConditions.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__CONDITIONS: return ModelPackage.CONTAINS_CONDITIONS__CONDITIONS;
				default: return -1;
			}
		}
		if (baseClass == CanBeSynced.class) {
			switch (derivedFeatureID) {
				default: return -1;
			}
		}
		if (baseClass == Accessible.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__ON_ACCESS: return ModelPackage.ACCESSIBLE__ON_ACCESS;
				default: return -1;
			}
		}
		if (baseClass == ActionSource.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__OUT_ACTIONS: return ModelPackage.ACTION_SOURCE__OUT_ACTIONS;
				default: return -1;
			}
		}
		if (baseClass == ContainsProperties.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__PROPERTIES: return ModelPackage.CONTAINS_PROPERTIES__PROPERTIES;
				default: return -1;
			}
		}
		if (baseClass == Scope.class) {
			switch (derivedFeatureID) {
				case ScopesPackage.EMAIL__ENTRY_GATE: return ModelPackage.SCOPE__ENTRY_GATE;
				case ScopesPackage.EMAIL__EXIT_GATE: return ModelPackage.SCOPE__EXIT_GATE;
				case ScopesPackage.EMAIL__VALUES: return ModelPackage.SCOPE__VALUES;
				case ScopesPackage.EMAIL__PARAMETERS: return ModelPackage.SCOPE__PARAMETERS;
				case ScopesPackage.EMAIL__ELEMENTS: return ModelPackage.SCOPE__ELEMENTS;
				case ScopesPackage.EMAIL__ON_INIT: return ModelPackage.SCOPE__ON_INIT;
				case ScopesPackage.EMAIL__SCOPES: return ModelPackage.SCOPE__SCOPES;
				default: return -1;
			}
		}
		return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass) {
		if (baseClass == ContainsOperations.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_OPERATIONS__OPERATIONS: return ScopesPackage.EMAIL__OPERATIONS;
				default: return -1;
			}
		}
		if (baseClass == GeneratesElements.class) {
			switch (baseFeatureID) {
				case ModelPackage.GENERATES_ELEMENTS__GENERATED_ELEMENTS: return ScopesPackage.EMAIL__GENERATED_ELEMENTS;
				case ModelPackage.GENERATES_ELEMENTS__OVERRIDDEN: return ScopesPackage.EMAIL__OVERRIDDEN;
				default: return -1;
			}
		}
		if (baseClass == ContainsWires.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_WIRES__WIRES: return ScopesPackage.EMAIL__WIRES;
				case ModelPackage.CONTAINS_WIRES__ACTIONS: return ScopesPackage.EMAIL__ACTIONS;
				case ModelPackage.CONTAINS_WIRES__PARAMETER_EDGES: return ScopesPackage.EMAIL__PARAMETER_EDGES;
				case ModelPackage.CONTAINS_WIRES__EXTENDS_EDGES: return ScopesPackage.EMAIL__EXTENDS_EDGES;
				case ModelPackage.CONTAINS_WIRES__REQUIRES_EDGES: return ScopesPackage.EMAIL__REQUIRES_EDGES;
				case ModelPackage.CONTAINS_WIRES__PROVIDES_EDGES: return ScopesPackage.EMAIL__PROVIDES_EDGES;
				case ModelPackage.CONTAINS_WIRES__CONSTRAINT_EDGES: return ScopesPackage.EMAIL__CONSTRAINT_EDGES;
				case ModelPackage.CONTAINS_WIRES__CONDITION_EDGES: return ScopesPackage.EMAIL__CONDITION_EDGES;
				default: return -1;
			}
		}
		if (baseClass == ShouldntContainWires.class) {
			switch (baseFeatureID) {
				default: return -1;
			}
		}
		if (baseClass == WireSource.class) {
			switch (baseFeatureID) {
				case ModelPackage.WIRE_SOURCE__OUT_WIRES: return ScopesPackage.EMAIL__OUT_WIRES;
				default: return -1;
			}
		}
		if (baseClass == WireDestination.class) {
			switch (baseFeatureID) {
				case ModelPackage.WIRE_DESTINATION__IN_WIRES: return ScopesPackage.EMAIL__IN_WIRES;
				default: return -1;
			}
		}
		if (baseClass == ContainsConditions.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_CONDITIONS__CONDITIONS: return ScopesPackage.EMAIL__CONDITIONS;
				default: return -1;
			}
		}
		if (baseClass == CanBeSynced.class) {
			switch (baseFeatureID) {
				default: return -1;
			}
		}
		if (baseClass == Accessible.class) {
			switch (baseFeatureID) {
				case ModelPackage.ACCESSIBLE__ON_ACCESS: return ScopesPackage.EMAIL__ON_ACCESS;
				default: return -1;
			}
		}
		if (baseClass == ActionSource.class) {
			switch (baseFeatureID) {
				case ModelPackage.ACTION_SOURCE__OUT_ACTIONS: return ScopesPackage.EMAIL__OUT_ACTIONS;
				default: return -1;
			}
		}
		if (baseClass == ContainsProperties.class) {
			switch (baseFeatureID) {
				case ModelPackage.CONTAINS_PROPERTIES__PROPERTIES: return ScopesPackage.EMAIL__PROPERTIES;
				default: return -1;
			}
		}
		if (baseClass == Scope.class) {
			switch (baseFeatureID) {
				case ModelPackage.SCOPE__ENTRY_GATE: return ScopesPackage.EMAIL__ENTRY_GATE;
				case ModelPackage.SCOPE__EXIT_GATE: return ScopesPackage.EMAIL__EXIT_GATE;
				case ModelPackage.SCOPE__VALUES: return ScopesPackage.EMAIL__VALUES;
				case ModelPackage.SCOPE__PARAMETERS: return ScopesPackage.EMAIL__PARAMETERS;
				case ModelPackage.SCOPE__ELEMENTS: return ScopesPackage.EMAIL__ELEMENTS;
				case ModelPackage.SCOPE__ON_INIT: return ScopesPackage.EMAIL__ON_INIT;
				case ModelPackage.SCOPE__SCOPES: return ScopesPackage.EMAIL__SCOPES;
				default: return -1;
			}
		}
		return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuffer result = new StringBuffer(super.toString());
		result.append(" (isGenerated: ");
		result.append(isGenerated);
		result.append(", id: ");
		result.append(id);
		result.append(", generatedRule: ");
		result.append(generatedRule);
		result.append(", name: ");
		result.append(name);
		result.append(", overridden: ");
		result.append(overridden);
		result.append(", to: ");
		result.append(to);
		result.append(", subject: ");
		result.append(subject);
		result.append(", toName: ");
		result.append(toName);
		result.append(", from: ");
		result.append(from);
		result.append(", fromName: ");
		result.append(fromName);
		result.append(')');
		return result.toString();
	}

} //EmailImpl
