#created on: 4/11/2008
package org.openiaml.model.drools

#list any import classes here.
import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.domain.*;

#declare any global variables here
global EcoreCreateElementsHelper handler;

rule "Create 'edit' event trigger for input text field"
	when
		f : InputTextField( overridden == false )
		not (EventTrigger( eContainer == f, name=="edit" ))
			
	then
		// debug: System.out.println(drools.getRule().getName() + ": " + f); 

		EventTrigger event = handler.generatedEventTrigger(f, f);
		event.setName("edit");
		insert(event);
		
end

rule "Create 'edit' event trigger for abstract domain attribute"
	when
		f : AbstractDomainAttribute( overridden == false )
		not (EventTrigger( eContainer == f, name=="edit" ))
			
	then
		EventTrigger event = handler.generatedEventTrigger(f, f);
		event.setName("edit");
		insert(event);
		
end

rule "Create 'access' event trigger for input text field"
	when
		f : InputTextField( overridden == false )
		not (EventTrigger( eContainer == f, name=="access" ))
			
	then
		EventTrigger event = handler.generatedEventTrigger(f, f);
		event.setName("access");
		insert(event);
		
end
