package org.openiaml.model.drools

#list any import classes here.
import org.eclipse.emf.ecore.*;
import org.openiaml.model.inference.*;
import org.openiaml.model.model.*;
import org.openiaml.model.model.impl.*;
import org.openiaml.model.model.wires.*;
import org.openiaml.model.model.visual.*;
import org.openiaml.model.model.operations.*;
import org.openiaml.model.model.domain.*;
import ca.ecliptical.emf.xpath.*;
import java.util.*;

#declare any global variables here
global EcoreCreateElementsHelper handler;

# TODO can we put this function into something global?
function boolean connects(WireEdge wire, Object a, Object b) {
	return (wire.getFrom().equals(a) && wire.getTo().equals(b)) ||
		(wire.getFrom().equals(b) && wire.getTo().equals(a));
}

rule "Connect ConditionWires to RunInstanceWires created by SyncWires"
	when
		sw : SyncWire(overridden == false)
		source : ContainsOperations( ) from sw.to
		target : ContainsEventTriggers( ) from sw.from  
		
		event : EventTrigger( eContainer == source, name=="edit" )
		operation : Operation( eContainer == target, name=="update" )
		
		run : RunInstanceWire( eContainer == sw, from == event, to == operation, name == "run" )
		condition : Condition ( )
		originalConditionWire : ConditionWire( from == condition, to == sw )
		
		not (ConditionWire (eContainer == originalConditionWire, from == condition, to == run )) 
		
	then
		ConditionWire cw = handler.generatedConditionWire( originalConditionWire, originalConditionWire, condition, run );
		cw.setName("copied condition: " + originalConditionWire.getName());
		insert(cw);

end

rule "Connect ParameterWires to ConditionWires connected to RunInstanceWires created by SyncWires"
	when
		sw : SyncWire(overridden == false)
		target : ContainsEventTriggers( ) from sw.from  
		source : ContainsOperations( ) from sw.to
		
		event : EventTrigger( eContainer == source, name=="edit" )
		operation : Operation( eContainer == target, name=="update" )
		
		run : RunInstanceWire( eContainer == sw, from == event, to == operation, name == "run" )
		condition : Condition ( )
		originalConditionWire : ConditionWire( from == condition, to == sw )
		
		cw : ConditionWire (eContainer == originalConditionWire, from == condition, to == run ) 
		
		paramSource : WireEdgesSource ( )
		paramWire : ParameterWire( from == paramSource, to == originalConditionWire )
		not (ParameterWire (eContainer == originalConditionWire, from == paramSource, to == cw ))
		
	then
		ParameterWire pw = handler.generatedParameterWire( originalConditionWire, originalConditionWire, paramSource, cw );
		//cw.setName("copied parameter: " + paramWire.getName());
		insert(cw);

end


rule "Connect ConditionWires to RunInstanceWires created by SyncWires (reverse)"
	when
		sw : SyncWire(overridden == false)
		source : ContainsEventTriggers( ) from sw.from  
		target : ContainsOperations( ) from sw.to
		
		event : EventTrigger( eContainer == source, name=="edit" )
		operation : Operation( eContainer == target, name=="update" )
		
		run : RunInstanceWire( eContainer == sw, from == event, to == operation, name == "run" )
		condition : Condition ( )
		originalConditionWire : ConditionWire( from == condition, to == sw )
		
		not (ConditionWire (eContainer == originalConditionWire, from == condition, to == run )) 
		
	then
		ConditionWire cw = handler.generatedConditionWire( originalConditionWire, originalConditionWire, condition, run );
		cw.setName("copied condition: " + originalConditionWire.getName());
		insert(cw);

end

rule "Connect ParameterWires to ConditionWires connected to RunInstanceWires created by SyncWires (reverse)"
	when
		sw : SyncWire(overridden == false)
		source : ContainsEventTriggers( ) from sw.from  
		target : ContainsOperations( ) from sw.to
		
		event : EventTrigger( eContainer == source, name=="edit" )
		operation : Operation( eContainer == target, name=="update" )
		
		run : RunInstanceWire( eContainer == sw, from == event, to == operation, name == "run" )
		condition : Condition ( )
		originalConditionWire : ConditionWire( from == condition, to == sw )
		
		cw : ConditionWire (eContainer == originalConditionWire, from == condition, to == run ) 
		
		paramSource : WireEdgesSource ( )
		paramWire : ParameterWire( from == paramSource, to == originalConditionWire )
		not (ParameterWire (eContainer == originalConditionWire, from == paramSource, to == cw ))
		
	then
		ParameterWire pw = handler.generatedParameterWire( originalConditionWire, originalConditionWire, paramSource, cw );
		//cw.setName("copied parameter: " + paramWire.getName());
		insert(cw);

end

